# Read the Docs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "miniforge3-latest"
  jobs:
    post_checkout:
      - git fetch origin --tags --force
    pre_create_environment:
      - conda config --set solver libmamba
      - conda info | grep -i solver
    post_install:
      - make info

sphinx:
  configuration: doc/source/conf.py
  builder: html
  fail_on_warning: false

conda:
  environment: doc/environment.yaml

python:
  install:
    - method: pip
      path: .
