// AUTO-GENERATED by script/gen-vitest-fixture.mjs from foliplus/_schema.py.
// Do not edit by hand — regenerate with:
//   python foliplus/_schema.py --out .foliplus/conf-schema.json
//   node script/gen-vitest-fixture.mjs
import type { ComponentConfig } from "#foliplus/conf-schema.js";

/**
 * Create a test CONF object pre-populated with every default value from
 * the Python schema. Pass overrides to customize specific fields.
 */
function makeConf(overrides?: Partial<ComponentConfig>): ComponentConfig {
  return {
    filename: "measurements",
    format: "png",
    quality: 0.92,
    scale: 2,
    max_pixels: 10240000,
    timeout: 7500,
    hide_self: true,
    hide_others: true,
    color_scheme: "Reds",
    method: "jenks",
    n_classes: 6,
    agg: "count",
    schemes: ["Blues", "Greens", "Reds", "Oranges", "Purples", "YlOrRd", "Viridis"],
    border_weight: 1.5,
    border_color: "#333333",
    fill_opacity: 0.7,
    border_opacity: 0.9,
    label_show: true,
    label_color: "#fff",
    label_size: 11,
    label_format: "auto",
    collapse_on_outside: true,
    label_collide: true,
    data: [],
    zoom: 15,
    show_bearing: true,
    show_live_coords: true,
    export_format: "geojson",
    show_zoom: true,
    mode: "coord",
    provider: "nominatim",
    ...overrides,
  };
}

export { makeConf };
