// AUTO-GENERATED by script/gen-conf-fixture.mjs from foliplus/_schema.py.
// Do not edit by hand — regenerate with:
//   node script/gen-conf-fixture.mjs

import type { ComponentConfig } from "#foliplus/conf-schema.js";

/** Default CONF values per control, from the Python schema. */
const CONF_DEFAULTS: Record<string, Partial<ComponentConfig>> = {
  ExportControl: {
    filename: "map",
    format: "png",
    max_pixels: 10240000,
    quality: 0.92,
    scale: 2,
    timeout: 7500,
  },
  FullscreenControl: {
    hide_others: true,
    hide_self: true,
  },
  HeatmapControl: {
    agg: "count",
    border_color: "#333333",
    border_opacity: 0.9,
    border_weight: 1.5,
    collapse_on_outside: true,
    color_scheme: "Reds",
    fill_opacity: 0.7,
    label_color: "#fff",
    label_format: "auto",
    label_show: true,
    label_size: 11,
    method: "jenks",
    n_classes: 6,
    schemes: [
      "Blues",
      "Greens",
      "Reds",
      "Oranges",
      "Purples",
      "YlOrRd",
      "Viridis",
    ],
  },
  LayerControl: {
    collapse_on_outside: false,
    data: [],
    label_collide: true,
  },
  LocateControl: {
    zoom: 15,
  },
  MeasureControl: {
    collapse_on_outside: true,
    export_format: "geojson",
    filename: "measurements",
    label_collide: true,
    label_show: true,
    show_bearing: true,
    show_live_coords: true,
  },
  ScaleControl: {
    show_zoom: true,
  },
  SearchControl: {
    collapse_on_outside: true,
    mode: "coord",
    provider: "nominatim",
    provider_config: null,
    zoom: 15,
  },
};

/**
 * Create a test CONF object for one control: shared test baseline (name,
 * position, locale_code) + that control's schema defaults + overrides.
 */
function makeConf(
  controlName: string,
  overrides?: Partial<ComponentConfig>,
): ComponentConfig {
  return {
    name: controlName,
    position: "topleft",
    locale_code: "en",
    ...CONF_DEFAULTS[controlName],
    ...overrides,
  };
}

export { makeConf };
