"""CONFIG contract between Python and JS, derived from ``__init__`` signatures.

A control declares its configuration surface where it belongs — in its own
``__init__`` signature. :func:`derive_schema` reflects that signature and
produces the :class:`ControlSchema` dict the two downstream surfaces are
generated from:

1. ``BaseControl._config_fields`` (Python serialization side) — derived by
   ``BaseControl.__init_subclass__`` from the schema's non-runtime-only keys,
   in signature order. No control module writes its own tuple.
2. ``foliplus/js/config-schema.ts`` (TS ``ComponentConfig`` type) — generated
   by ``script/build/emit-config-schema.mjs`` from the same dump.
3. ``test/js/config-fixture.ts`` (vitest CONFIG fixture) — generated by
   ``test/js/script/emit-config-fixture.mjs`` from the same dump.

**Type tags are TS type names.** A field's ``ts`` value is either a TS
primitive construction (``"bool"`` / ``"number"`` / ``"string"`` / ``"null"``
/ ``"any"`` / ``"union"``) or the name of a type exported from somewhere in
``foliplus/js`` (``"NumberStyle"``, ``"ControlPosition"``, ``"LayerData"`` …).
The mapping is the identity: there is no internal codename layer between the
Python tag and the TS type it renders as. :func:`verify_tags` checks every tag
that renders as a type name against :data:`IMPORTS` (the type names available
to ``config-schema.ts``), so a tag typo or a rename on one side fails the dump
instead of emitting an unimported type into the generated TS.

Special-cased (not bare type names):

* ``"Record<string, ...>"`` / ``"string[]"`` / ``"unknown[]"`` — inline TS
  constructs, not imported names.
* ``"string | ProviderConfig"`` — the SearchControl ``provider`` field is a
  union of a built-in provider id and a custom ``ProviderConfig`` dict; the tag
  renders the union inline because Python has no alias to name that union.

**Values decide the CONFIG contract.** Nothing in this module is consulted at
render time: ``BaseControl._build_config`` reads ``self._config_fields``
(derived once, at class-definition time) and never touches these tables. The
schema is what :meth:`BaseControl.__init_subclass__` reads to derive
``_config_fields``, so a signature change is a *contract change*, not a
cosmetic one — the existing Python tests snapshot the emitted JSON and fail on
drift.

Usage (build tooling):

    python foliplus/_config_schema.py --dump                                    # stdout
    python foliplus/_config_schema.py --out foliplus/.build/js/config-schema.json  # file

    # Or via python -m (requires branca/folium installed):
    python -m foliplus._config_schema --dump
"""

from __future__ import annotations

import argparse
import inspect
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from types import UnionType
from typing import (
    TYPE_CHECKING,
    Annotated,
    Any,
    Literal,
    Union,
    get_args,
    get_origin,
    get_type_hints,
)

if TYPE_CHECKING:
    # Type-only: BaseControl imports this module at runtime, so a real import
    # here would be circular. Annotations are strings under __future__.
    from .BaseControl import BaseControl

# When run as `python foliplus/_config_schema.py`, the script's directory is prepended
# to sys.path. This shadows stdlib `locale` with `foliplus/locale` (which has
# no `normalize()`), breaking argparse's gettext import. Strip the script dir
# so stdlib modules resolve correctly. Safe: `_config_schema.py` imports no foliplus
# siblings, so it does not need the package on sys.path.
_script_dir = str(Path(__file__).resolve().parent)
if _script_dir in sys.path:
    sys.path.remove(_script_dir)

# TS type tags supported. Primitives are TS construction instructions; every
# other tag is a type name exported by `foliplus/js` (or an inline TS
# construct, listed here so the generator can render it). Add a new tag only
# when a real control needs it; the generator refuses unknown tags so a typo
# fails the build rather than emitting a bogus type.
_TS_PRIMITIVES: dict[str, str] = {
    "bool": "boolean",
    "number": "number",
    "string": "string",
    "any": "unknown",
    "null": "null",
}
_TS_OBJECTS: dict[str, str] = {
    "object": "Record<string, unknown>",
    "object_string": "Record<string, string>",
    "object_nested": "Record<string, Record<string, string>>",
    "array_string": "string[]",
    "array_unknown": "unknown[]",
    # `locale_tables` is the shared locale table shape; imported from
    # #common/locale.js in the generated TS.
    "LocaleTables": "LocaleTables",
    # `NumberStyle` is the HeatmapControl label_format tag; imported from
    # #common/format.js.
    "NumberStyle": "NumberStyle",
    # LayerControl's dynamic `data` field — the layer list collected from the
    # parent map at render time. Shape is an array of small label descriptors.
    "LayerData": 'Array<{ name: string; id: string; group: "base" | "overlay" }>',
    # `ControlPosition` is the Leaflet control position — a string literal
    # union imported from Leaflet in the generated TS.
    "ControlPosition": "ControlPosition",
    # `provider` is `str | dict` — the string is a built-in provider id, the
    # dict is a custom ProviderConfig. Kept as a special tag so the emitted
    # TS reads `string | ProviderConfig` (typed via ProviderConfig in
    # global.d.ts) rather than the generic `Record<string, unknown>`. Not a
    # bare type name, so it is excluded from verify_tags()' import check.
    "string | ProviderConfig": "string | ProviderConfig",
}
_SUPPORTED_TAGS = set(_TS_PRIMITIVES) | set(_TS_OBJECTS)
_TS_OBJECTS["ProviderConfig"] = "Record<string, unknown>"

# Type names the generated `config-schema.ts` imports. Mirrored by
# `script/build/emit-config-schema.mjs`'s IMPORTS; verify_tags() checks that
# every tag which resolves to a type name is either here or an inline
# construct (Record/[]), so the two files cannot drift apart silently.
IMPORTS: dict[str, str] = {
    "ControlPosition": "leaflet",
    "LocaleTables": "#common/locale.js",
    "NumberStyle": "#common/format.js",
    "ProviderConfig": "#core/geocode/type.js",
}

# Tags that render to a TS construct rather than an imported name.
_INLINE_TAGS = {"Record<string, unknown>", "string[]", "unknown[]"}


# Sentinel distinguishing "no default declared" from an explicit null/None
# default. `default: Any = None` cannot carry that distinction — a field whose
# real default is None (e.g. SearchControl.provider_config) would be treated
# as "no default" and dropped from the dump. Anything JSON-serializable is a
# legal default, including None.
_UNSET = object()


@dataclass(frozen=True)
class FieldSpec:
    """Declarative spec for one CONFIG field.

    Attributes
    ----------
    ts
        Base type tag. One of :data:`_SUPPORTED_TAGS`, or ``"union"`` — in
        the union case, :attr:`values` must be set and renders as
        ``"a" | "b" | "c"``.
    optional
        Field may be absent at runtime (JSON `undefined`). Renders ``?`` in
        TS. All runtime_only fields are optional by construction.
    nullable
        Field may be JSON ``null`` in addition to its base type. Renders
        ``X | null`` in TS.
    values
        For ``ts="union"``, the tuple of string literal values.
    item
        For array tags, the item type tag (rarely used; most arrays are
        ``array_string``). Kept for extensibility; unused today.
    runtime_only
        JS sets this field at runtime; Python never emits it. Excluded from
        ``BaseControl._config_fields``; declared in TS and vitest fixture.
    dynamic
        Python emits this field at render time via ``_extra_config`` (not a
        static ``_config_fields`` key). Excluded from ``_config_fields`` but
        included in the TS type and vitest fixture.
    default
        JSON-serializable default used by the vitest fixture. Must be a
        value a Python dict can hold (str, int, float, bool, list, dict,
        or None). ``None`` is a *real* default and is serialized as JSON
        ``null``; :data:`_UNSET` (the dataclass default) means "no default
        declared — omit from fixture" (used for fields whose default is a
        runtime decision, e.g. ``locale_tables``).
    note
        Human-readable note, rendered into the generated TS: a short
        single-line note becomes a trailing ``//`` comment on the field,
        a longer or multi-line one becomes a ``/** */`` block above it.
        Empty means no comment.
    """

    ts: str
    optional: bool = False
    nullable: bool = False
    values: tuple[str, ...] | None = None
    item: str | None = None
    runtime_only: bool = False
    dynamic: bool = False
    default: Any = _UNSET
    note: str = ""

    def __post_init__(self) -> None:
        if self.ts == "union":
            if not self.values:
                raise ValueError(f"FieldSpec(ts='union') requires values, got None")
        elif not self.ts and not self.values:
            # A metadata-only FieldSpec (note, nullable, …) carries no tag.
            # The tag is decided by the reflector; ``ts=""`` means "no
            # override", which is distinct from a typo and must not raise
            # here — an empty tag is not in _SUPPORTED_TAGS by design.
            pass
        elif self.ts not in _SUPPORTED_TAGS:
            raise ValueError(
                f"FieldSpec ts={self.ts!r} is not a supported tag; "
                f"valid: {sorted(set(_SUPPORTED_TAGS) | {'union'})}"
            )
        if self.runtime_only and not self.optional:
            # A field Python never emits can only be present at runtime;
            # it is therefore always optional in TS.
            raise ValueError(
                f"runtime_only field must be optional (was optional={self.optional})"
            )
        if self.dynamic and self.runtime_only:
            raise ValueError(
                "dynamic and runtime_only are mutually exclusive — a field is "
                "either emitted by Python (static or dynamic) or set by JS."
            )


ControlSchema = dict[str, FieldSpec]


def render_ts_type(spec: FieldSpec) -> str:
    """Render the TS type for one field spec.

    Combines the base tag with the nullable suffix. Raises on unknown tags
    so a typo in a schema entry fails at dump time rather than silently
    emitting a bogus type into the TS surface.
    """
    if spec.ts == "union":
        # __post_init__ guarantees values for union; assert so mypy narrows.
        assert spec.values is not None
        base = " | ".join(f'"{v}"' for v in spec.values)
    elif spec.ts in _TS_PRIMITIVES:
        base = _TS_PRIMITIVES[spec.ts]
    elif spec.ts in _TS_OBJECTS:
        base = _TS_OBJECTS[spec.ts]
    else:
        raise ValueError(f"unknown FieldSpec.ts={spec.ts!r}")
    if spec.nullable:
        return f"{base} | null"
    return base


def verify_tags(tags: set[str]) -> None:
    """Fail loud when a tag renders as a type name that is not imported.

    Every tag is either a TS primitive, an inline TS construct
    (``Record<...>`` / ``string[]``), or the name of a type the generated
    ``config-schema.ts`` imports. Anything else is a typo or a rename that
    landed on one side only — emit nothing rather than an unimported type
    that type-checks nowhere.
    """
    bad = sorted(
        t
        for t in tags
        if t not in _SUPPORTED_TAGS | {"union"}
        and _TS_OBJECTS.get(t) not in _INLINE_TAGS
        and _TS_OBJECTS.get(t) not in IMPORTS
        and t != "string | ProviderConfig"
    )
    if bad:
        raise ValueError(
            "tags render to a type name that config-schema.ts does not import "
            f"({sorted(IMPORTS)}): {bad} — add the import to "
            "script/build/emit-config-schema.mjs IMPORTS and to "
            "foliplus/_config_schema.IMPORTS"
        )


# ── Shared (BaseControl) fields ──────────────────────────────────────────
# Emitted by every control via ``BaseControl._build_config`` /
# ``_config_block``. Not part of any control's ``_config_fields`` (they are
# the base's job), but part of the CONFIG contract every control sees.

SHARED: ControlSchema = {
    "name": FieldSpec("string", note="Control class name (Python self._name)."),
    "position": FieldSpec(
        "ControlPosition", optional=True, note="Leaflet control position."
    ),
    "locale_tables": FieldSpec(
        "LocaleTables",
        optional=True,
        note="Locale tables written by BaseControl._config_block.",
    ),
    "locale_code": FieldSpec(
        "string", optional=True, note="Resolved locale code (empty when unset)."
    ),
}

# ── Runtime-only fields (JS declares but Python never emits) ─────────────
# Currently both are declared in global.d.ts but never read from CONFIG by
# production JS — they are dead declarations kept for forward compatibility.
# Marking them here means the schema is a complete contract surface and the
# vitest fixture knows they can appear on CONFIG without Python emitting them.

RUNTIME_ONLY: ControlSchema = {
    "field": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Annotation field name (JS reads per-layer config, not CONFIG).",
    ),
    "background": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Export background color (currently declared but unread).",
    ),
}


# ── Reflection ─────────────────────────────────────────────────────────────
# A control's ``__init__`` signature *is* its schema. These tables translate
# the annotation of each parameter into a TS tag; everything they cannot
# decide is resolved by a ``FieldSpec(...)`` metadata attached to the type
# alias it is declared with (see ``foliplus/_typing.py``).

# Bare Python type → TS tag, for annotations the reflector can decide alone.
_PRIMITIVES: dict[type, str] = {
    str: "string",
    bool: "bool",
    int: "number",
    float: "number",
}
_ARRAY_TAGS: dict[tuple[type, ...], str] = {
    (str,): "array_string",
    (Any,): "array_unknown",
}
_DICT_TAGS: dict[tuple[type, ...], str] = {
    (Any, Any): "object",
    (str, Any): "object",
    (str, str): "object_string",
    (str, dict): "object_nested",
}

# ``BaseControl.__init__`` parameters that are the base class's job. A
# subclass that redeclares one in its own signature does not export it as a
# CONFIG field — it is already covered by :data:`SHARED`.
_SHARED_PARAMS: frozenset[str] = frozenset({"position", "locale"})

# A dynamic field declares its own hint next to itself on the class —
# ``_data_hint`` carries the TS shape for the ``data`` field. The tag is a
# name the generated TS imports, not a bare type.
_DYNAMIC_HINT_ATTR: dict[str, str] = {
    "data": "_dynamic_data_hint",
}

_DYNAMIC_FALLBACK: dict[str, str] = {
    "data": "LayerData",
}


def _field_spec_in(*args: Any) -> FieldSpec | None:
    """Return the ``FieldSpec`` among ``Annotated`` metadata, or ``None``.

    ``Annotated[T, Bound(...), FieldSpec(...)]`` carries both channels:
    ``Bound`` is consumed by ``@validate`` at call time, ``FieldSpec`` here
    at schema-derivation time. Anything else (e.g. ``Annotated[int, 3]``) is
    neither and is ignored by both.
    """
    for item in args:
        if isinstance(item, FieldSpec):
            return item
    return None


def _evaluate(arg: Any) -> Any:
    """Resolve one ``Union`` arm that may still be a string.

    With `from __future__ import annotations` the arm of a spelled-out union
    (``list[str] | None``) can reach the reflector as the string ``"None"``
    rather than the type. Resolve it against the module's globals so a
    nullable union is recognised the same way whether it is spelled
    ``X | None`` or ``Optional[X]``.
    """
    if not isinstance(arg, str):
        return arg
    if arg == "None":
        return type(None)
    return eval(arg, globals())


def _is_nullable(hint: Any) -> bool:
    """Whether ``hint`` admits JSON ``null`` at its outermost level.

    Strips ``Annotated`` first: a tag override names the type, it does not
    license dropping the null. ``Annotated[ProviderConfig | None, FieldSpec(
    ts="object")]`` is still nullable.
    """
    origin = get_origin(hint)
    if origin is Annotated:
        return _is_nullable(get_args(hint)[0])
    if origin not in (Union, UnionType):
        return False
    arms = [_evaluate(a) for a in get_args(hint)]
    non_null = [a for a in arms if a is not type(None)]
    return len(non_null) == 1 and len(non_null) != len(arms)


def _resolve_tag(
    hint: Any, meta: FieldSpec | None
) -> tuple[str, tuple[str, ...] | None, bool, FieldSpec | None]:
    """Resolve one annotation to ``(tag, values, nullable, spec)``.

    ``spec`` is the author's ``FieldSpec`` metadata (or ``None``):
    :func:`derive_schema` reads ``optional`` and ``note`` from it. ``ts``,
    ``values`` and ``nullable`` are the reflector's own decision, reported
    separately so the caller can see what was decided and from where.

    Layers, in order of authority:

    1. An explicit ``FieldSpec(ts=...)`` — an override the author wrote
       because the automatic mapping cannot decide (a ``Literal`` that is
       really ``NumberStyle``, a ``str | dict`` union that is really
       ``ProviderConfig``, …).
    2. ``X | None`` — a nullable variant of whatever ``X`` resolves to.
    3. Bare Python type, ``Literal``, ``list[X]``, ``dict[K, V]``.

    ``peeled`` distinguishes a real ``Literal`` from a type alias that
    happens to be a ``Literal``: a bare ``Literal`` is a union, but a
    ``Literal`` wrapped in ``Annotated`` with a ``FieldSpec`` is the alias.
    """
    origin = get_origin(hint)
    # Peel Annotated for the base type whether or not it carries a FieldSpec:
    # ``Annotated[float, Bound(0.0, 1.0)]`` validates at call time and has
    # nothing to say about the TS tag, so ``base`` must reach ``float``.
    args = get_args(hint) if origin is Annotated else ()
    base = args[0] if args else hint
    inner_meta = _field_spec_in(*args[1:]) if args else None
    # A layer that carries no FieldSpec keeps the one passed down by an outer
    # layer: `Annotated[PositiveInt | None, FieldSpec(note=...)]` peels to
    # `Annotated[int, Bound(...)] | None`, whose Bound is not a FieldSpec, and
    # the note must survive that hop.
    meta = inner_meta or meta
    peeled = meta is not None

    if meta is not None and meta.ts:
        # The author named the type; nullability still comes from the
        # annotation, not from the override.
        return meta.ts, meta.values, _is_nullable(hint) or meta.nullable, meta

    if origin is Annotated:
        # No tag override, so the type to render is the annotated base. It may
        # itself be a union or another Annotated (PositiveInt is
        # Annotated[int, Bound(...)]), so recurse rather than re-implementing
        # the mapping below; the meta carries note and optional through.
        tag, values, nullable, inner_meta = _resolve_tag(base, meta)
        return tag, values, nullable, meta or inner_meta

    if origin in (Union, UnionType):
        arms = [_evaluate(a) for a in get_args(hint)]
        non_null = [a for a in arms if a is not type(None)]
        nullable = len(non_null) != len(arms)
        if len(non_null) == 1:
            tag, values, inner_nullable, _ = _resolve_tag(non_null[0], meta)
            return tag, values, nullable or inner_nullable, meta
        # A union of two unrelated arms is not a JSON shape: the author must
        # name it. ProviderConfig's `str | dict` reaches here as
        # `str | TypedDict` and carries FieldSpec(ts=...) for exactly this.
        raise ValueError(
            f"cannot map union annotation {hint!r} to a TS tag — add "
            "FieldSpec(ts=...) to name the union"
        )

    if origin is Literal:
        if not peeled:
            return "union", tuple(str(v) for v in get_args(hint)), False, meta
        raise ValueError(
            "a Literal alias needs FieldSpec(ts=...) to name its TS type; "
            "bare Literal unions are decided automatically"
        )

    if base in _PRIMITIVES:
        return _PRIMITIVES[base], None, False, None

    if get_origin(base) is list:
        return _ARRAY_TAGS.get(get_args(base), "array_unknown"), None, False, None

    if get_origin(base) is dict:
        return _DICT_TAGS.get(get_args(base), "object"), None, False, None

    raise ValueError(
        f"cannot map annotation {hint!r} to a TS tag — add FieldSpec(ts=...) "
        "to the type alias it is declared with, or extend _config_schema"
    )


def _is_json_serializable(value: Any) -> bool:
    """Return ``True`` when ``value`` can be held by the vitest fixture.

    The fixture is JSON; anything else a default could be (an enum member, a
    bound method, a path) would have to be serialized by hand, so the dump
    fails loud rather than emitting a non-JSON default.
    """
    return (
        value is None
        or isinstance(value, (str, int, float, bool))
        or (isinstance(value, list) and all(_is_json_serializable(v) for v in value))
        or (
            isinstance(value, dict)
            and all(_is_json_serializable(v) for v in value.values())
        )
    )


def derive_schema(cls: type[BaseControl]) -> ControlSchema:
    """Reflect ``cls.__init__`` into a :class:`ControlSchema`.

    Signature order becomes schema order, and schema order becomes
    ``_config_fields`` order, so a new parameter appended to a signature
    appends a CONFIG key — moving a parameter moves the key. Parameters
    inherited from ``BaseControl.__init__`` (``position``, ``locale``) are
    skipped: they are the base's job, already covered by :data:`SHARED`.

    Defaults must be JSON-serializable — the fixture is generated from them.
    A parameter whose default is a runtime decision (nothing the author can
    write in a signature) raises; such a field is either dynamic
    (:attr:`BaseControl._dynamic_fields`) or should not be a CONFIG field at
    all.
    """
    init = cls.__init__
    sig = inspect.signature(init)
    hints = get_type_hints(init, include_extras=True)
    out: ControlSchema = {}
    for name, param in sig.parameters.items():
        if name == "self" or name == "return" or name in _SHARED_PARAMS:
            continue

        hint = hints.get(name, param.annotation)
        has_default = param.default is not inspect._empty  # noqa: SLF001

        # Order matters: a missing default is a declaration error (the field
        # cannot be a CONFIG field at all), so it is reported before the
        # annotation is mapped — otherwise an author sees a tag error for a
        # parameter they did not intend to export.
        if not has_default:
            raise ValueError(
                f"{cls.__name__}.{name} has no default — a CONFIG field without a "
                "default is emitted only if JS sets it (runtime_only), which "
                "cannot be declared in a signature"
            )

        tag, values, nullable, meta = _resolve_tag(hint, None)
        if not _is_json_serializable(param.default):
            raise ValueError(
                f"{cls.__name__}.{name} default {param.default!r} is not JSON "
                "serializable — the vitest fixture is generated from it"
            )

        # Reflection decides the tag; the author's FieldSpec decides the
        # render-time attributes. `optional` defaults to False: Python emits
        # every non-runtime, non-dynamic field, so the per-control TS interface
        # declares it required — runtime_only and dynamic carry optionality.
        spec = FieldSpec(
            ts=tag,
            values=values,
            nullable=nullable,
            optional=meta.optional if meta else False,
            default=param.default,
            note=meta.note if meta else "",
        )
        out[name] = spec

    # Dynamic fields are collected at render time (LayerControl's ``data``),
    # so they are not parameters — the class declares them here. The TS
    # shape is carried by a hint attribute on the class (``_data_hint``);
    # it is a name, not a bare type, so no reflection is needed.
    for name in getattr(cls, "_dynamic_fields", ()):
        if name in out:
            raise ValueError(
                f"{cls.__name__}.{name} is declared both in the signature and "
                "in _dynamic_fields — a dynamic field is not a parameter"
            )
        tag = getattr(
            cls,
            _DYNAMIC_HINT_ATTR.get(name, f"_{name}_hint"),
            _DYNAMIC_FALLBACK.get(name, "object"),
        )
        out[name] = FieldSpec(
            ts=tag,
            dynamic=True,
            optional=True,
            default=[],
            note="Layer list collected from the parent map at render time via _extra_config.",
        )

    return out


# ── Per-control schemas ──────────────────────────────────────────────────
# Order within a control's schema is signature order — the derived
# ``_config_fields`` tuple inherits it verbatim, so a reordered signature
# reorders the exported CONFIG keys.


def config_fields(schema: ControlSchema) -> tuple[str, ...]:
    """Fields Python emits to CONFIG for one control (non-runtime, non-dynamic keys).

    Order is declaration order. Called by BaseControl's
    ``__init_subclass__``, which assigns the result to ``_config_fields`` —
    the schema is the single source and the tuple inherits this order.
    Dynamic and runtime-only fields are intentionally excluded — dynamic
    fields are emitted via ``_extra_config`` and runtime-only fields are
    JS-set.
    """
    return tuple(k for k, f in schema.items() if not f.runtime_only and not f.dynamic)


def schema_to_json() -> str:
    """Serialize the whole schema table to JSON (deterministic, sorted).

    The dumped shape is what ``script/build/emit-config-schema.mjs`` and
    ``test/js/script/emit-config-fixture.mjs`` consume. Kept stable: adding a new
    ``FieldSpec`` attribute is a schema version bump, not a silent change.

    Every tag is checked against :data:`IMPORTS` first (:func:`verify_tags`) so
    a tag that renders to a type name the generated TS does not import fails
    here rather than as an unimported type in ``config-schema.ts``.

    Must not touch ``sys.path`` or ``sys.modules``: in-process callers (pytest)
    already hold a live ``foliplus`` import, and re-importing the package would
    hand the reflector a second ``FieldSpec`` class — the ``isinstance`` check
    in :func:`_field_spec_in` would then stop finding the ``Annotated``
    metadata and every typed field would fail to resolve. Path pinning for
    script mode lives in ``__main__`` below.
    """
    from foliplus import BaseControl

    control_schemas = _derived_control_schemas(BaseControl)
    payload = {
        "version": 1,
        "shared": _field_dict_list(SHARED),
        "runtime_only": _field_dict_list(RUNTIME_ONLY),
        "controls": {
            name: _field_dict_list(schema) for name, schema in control_schemas
        },
    }
    verify_tags(collect_tags(SHARED, RUNTIME_ONLY, *(s for _, s in control_schemas)))
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _pin_package_path(
    keep: tuple[str, ...] = (),
) -> None:  # pragma: no cover - script bootstrap: runpy subprocess test
    """Force ``foliplus`` to resolve to this module's own package.

    Needed only when this file runs as a script: ``python foliplus/_config_schema.py``
    prepends the script's directory to ``sys.path``, which is stripped on import
    (it shadows stdlib ``locale``), so ``import foliplus`` would fall back to
    whatever an editable install resolves to — possibly a different checkout.
    Put the package's parent directory on ``sys.path`` first and drop any
    already-imported ``foliplus`` modules so the import picks up the siblings
    of this file.

    ``keep`` names modules to leave in ``sys.modules``: this file executing as
    a script registers itself under its package name first, so its siblings can
    import ``FieldSpec`` from it instead of loading a second copy.

    Never called from :func:`schema_to_json`: that would re-import ``foliplus``
    out from under an in-process caller and split class identity.
    """
    pkg_dir = str(Path(__file__).resolve().parent.parent)
    if pkg_dir in sys.path:
        sys.path.remove(pkg_dir)
    sys.path.insert(0, pkg_dir)
    for name in list(sys.modules):
        if name in keep:
            continue
        if name == "foliplus" or name.startswith("foliplus."):
            del sys.modules[name]
    import foliplus  # noqa: F401 -- re-import against the pinned path

    own_pkg_dir = str(Path(foliplus.__file__).resolve().parent.parent)
    if own_pkg_dir != pkg_dir:
        raise RuntimeError(
            f"foliplus resolves to {own_pkg_dir}, but this module lives in "
            f"{pkg_dir} — the editable-install path hook is overriding sys.path"
        )


def _derived_control_schemas(base: type) -> list[tuple[str, ControlSchema]]:
    """Reflect every shipped control, returning ``(name, schema)`` pairs."""
    return [
        (c.__name__, derive_schema(c))
        for c in sorted(
            (
                c
                for c in base.__subclasses__()
                if c.__module__.startswith("foliplus.")
                and not c.__name__.startswith("_")
            ),
            key=lambda c: c.__name__,
        )
    ]


def collect_tags(*schemas: ControlSchema) -> set[str]:
    """Every tag appearing in ``schemas`` (for :func:`verify_tags`)."""
    return {spec.ts for schema in schemas for spec in schema.values()}


def _field_dict_list(schema: ControlSchema) -> dict[str, dict[str, Any]]:
    """Convert one ControlSchema to a JSON-friendly dict of field dicts.

    Drops Python-only fields (``item``, ``note``) that the generators don't
    need — ``note`` is still kept so the generated TS carries docstrings.
    """
    out: dict[str, dict[str, Any]] = {}
    for name, spec in schema.items():
        entry: dict[str, Any] = {
            "ts": spec.ts,
            "optional": spec.optional or spec.runtime_only,
            "nullable": spec.nullable,
            "runtime_only": spec.runtime_only,
            "dynamic": spec.dynamic,
        }
        if spec.values is not None:
            entry["values"] = list(spec.values)
        if spec.note:
            entry["note"] = spec.note
        if spec.default is not _UNSET:
            entry["default"] = spec.default
        out[name] = entry
    return out


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="foliplus._config_schema",
        description="Dump the CONFIG schema as JSON for build tooling.",
    )
    parser.add_argument(
        "--dump",
        action="store_true",
        help="Print the schema JSON to stdout (default when --out is omitted).",
    )
    parser.add_argument(
        "--out",
        metavar="PATH",
        help="Write the schema JSON to PATH instead of stdout.",
    )
    args = parser.parse_args(argv)
    text = schema_to_json()
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    # As a script this file is not registered as foliplus._config_schema, so a
    # sibling doing `from ._config_schema import FieldSpec` would load a second
    # copy — a second FieldSpec class, which the isinstance() check in
    # _field_spec_in() would not match. Register this module first.
    sys.modules["foliplus._config_schema"] = sys.modules["__main__"]
    # sys.path[0] was this directory (stripped above), so pin the package path
    # before schema_to_json() imports foliplus.
    _pin_package_path(keep=("foliplus._config_schema",))
    raise SystemExit(_main())
