"""CONFIG contract between Python and JS, derived from ``__init__`` signatures.

A control declares its configuration surface where it belongs — in its own
``__init__`` signature. :func:`derive_schema` reflects that signature and
produces the :class:`ControlSchema` dict the two downstream surfaces are
generated from:

1. ``BaseControl._config_fields`` (Python serialization side) — derived by
   ``BaseControl.__init_subclass__`` from the schema's non-runtime-only keys,
   in signature order. No control module writes its own tuple.
2. ``foliplus/js/config-schema.ts`` (TS ``ComponentConfig`` type) and
   ``test/js/config-fixture.ts`` (vitest CONFIG fixture) — committed
   artifacts, regenerated by hand via ``script/build/emit-config-schema.mjs``
   and ``test/js/script/emit-config-fixture.mjs``; both read this schema's
   JSON dump. Drift is held by pytest (``test/python/test_config_schema.py``),
   not by the build, so ``npx vitest`` never spawns Python.

**Type tags are TS type names, or generated alias names.** A field's ``ts``
value is either a TS primitive (``"bool"`` / ``"number"`` / ``"string"`` /
``"null"`` / ``"any"`` / ``"union"``), a base-object tag that renders as an
inline TS construct (``"object"`` → ``Record<string, unknown>``, ``"object_string"``
→ ``Record<string, string>``, ``"object_nested"`` →
``Record<string, Record<string, string>>``, ``"array_string"`` / ``"array_unknown"``),
the special ``"ControlPosition"`` tag (imported from Leaflet), or the special
``"string | ProviderConfig"`` union tag.

Named type aliases — types that appear in the TS surface as named types
(``NumberStyle``, ``LayerData``, ``ProviderConfig`` …) — are declared via
:attr:`FieldSpec.name` together with a shape descriptor or a ``ts="union"`` +
``values`` pair. The generator emits the alias at the top of
``config-schema.ts`` and the field's TS type renders as the name. This is how
the shape of complex types stays in one place: Python's schema.

Special-cased (not bare type names):

* ``"Record<string, ...>"`` / ``"string[]"`` / ``"unknown[]"`` — inline TS
  constructs, rendered by base-object tags (see :data:`_TS_OBJECTS`).
* ``"string | ProviderConfig"`` — the SearchControl ``provider`` field is a
  union of a built-in provider id and a custom ``ProviderConfig`` dict; the tag
  renders the union inline because Python has no alias to name that union.

:func:`verify_tags` checks every tag against the union of
:data:`_SUPPORTED_TAGS` (primitives + base objects + ``ControlPosition`` +
the special union tag) and the set of generated alias names, so a tag typo or
a rename on one side fails the dump rather than emitting an unimported type
into the generated TS.

**Values decide the CONFIG contract.** Nothing in this module is consulted at
render time: ``BaseControl._build_config`` reads ``self._config_fields``
(derived once, at class-definition time) and never touches these tables. The
schema is what :meth:`BaseControl.__init_subclass__` reads to derive
``_config_fields``, so a signature change is a *contract change*, not a
cosmetic one — the existing Python tests snapshot the emitted JSON and fail on
drift.

Usage (Python tooling):

    python foliplus/_config_schema.py --dump                            # stdout
    python foliplus/_config_schema.py --out <path>                      # file

    # Or via python -m (requires branca/folium installed):
    python -m foliplus._config_schema --dump
"""

from __future__ import annotations

import argparse
import inspect
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from types import UnionType
from typing import (
    TYPE_CHECKING,
    Annotated,
    Any,
    Literal,
    Union,
    get_args,
    get_origin,
    get_type_hints,
)

if TYPE_CHECKING:
    # Type-only: BaseControl imports this module at runtime, so a real import
    # here would be circular. Annotations are strings under __future__.
    from .BaseControl import BaseControl

# When run as `python foliplus/_config_schema.py`, the script's directory is prepended
# to sys.path. This shadows stdlib `locale` with `foliplus/locale` (which has
# no `normalize()`), breaking argparse's gettext import. Strip the script dir
# so stdlib modules resolve correctly. Safe: `_config_schema.py` imports no foliplus
# siblings, so it does not need the package on sys.path.
_script_dir = str(Path(__file__).resolve().parent)
if _script_dir in sys.path:
    sys.path.remove(_script_dir)

# TS type tags supported. Primitives are TS construction instructions; every
# other tag is a type name exported by `foliplus/js` (or an inline TS
# construct, listed here so the generator can render it). Add a new tag only
# when a real control needs it; the generator refuses unknown tags so a typo
# fails the build rather than emitting a bogus type.
_TS_PRIMITIVES: dict[str, str] = {
    "bool": "boolean",
    "number": "number",
    "string": "string",
    "any": "unknown",
    "null": "null",
}
_TS_OBJECTS: dict[str, str] = {
    "object": "Record<string, unknown>",
    "object_string": "Record<string, string>",
    "object_nested": "Record<string, Record<string, string>>",
    "array_string": "string[]",
    "array_unknown": "unknown[]",
    # `ControlPosition` is the Leaflet control position — a string literal
    # union imported from Leaflet in the generated TS.
    "ControlPosition": "ControlPosition",
    # `provider` is `str | dict` — the string is a built-in provider id, the
    # dict is a custom ProviderConfig. Kept as a special tag so the emitted
    # TS reads `string | ProviderConfig` (typed via the ProviderConfig alias
    # generated in config-schema.ts) rather than the generic
    # `Record<string, unknown>`. Not a bare type name.
    "string | ProviderConfig": "string | ProviderConfig",
}
_SUPPORTED_TAGS = set(_TS_PRIMITIVES) | set(_TS_OBJECTS)

# Type names the generated `config-schema.ts` imports. Mirrored by
# `script/build/emit-config-schema.mjs`'s IMPORTS; verify_tags() checks that
# every tag is either a primitive/base-object/union, an entry here, or a
# generated named type (see :attr:`FieldSpec.name`).
IMPORTS: dict[str, str] = {
    "ControlPosition": "leaflet",
}


# Sentinel distinguishing "no default declared" from an explicit null/None
# default. `default: Any = None` cannot carry that distinction — a field whose
# real default is None (e.g. SearchControl.provider_config) would be treated
# as "no default" and dropped from the dump. Anything JSON-serializable is a
# legal default, including None.
_UNSET = object()

# One message for a shape descriptor attached to an annotation, raised either
# by :func:`_resolve_tag` (3.11+, where the descriptor is still reachable) or
# by :func:`derive_schema` (3.10, where get_type_hints aborts first — see
# the try/except there).
_SHAPE_IN_ANNOTATION_ERROR = (
    "FieldSpec.shape must not be attached to an Annotated type — a shape "
    "descriptor is unhashable and Python 3.10's get_type_hints() hashes "
    "Annotated metadata, so importing the module raises TypeError there. "
    "Declare it as a class attribute instead: _<name>_shape = ..."
)


# Shape descriptors: JSON-serializable trees describing a TS type. Grammar
# (validated by :func:`_validate_shape`):
#
# * ``"string"`` / ``"number"`` / ``"bool"`` / ``"null"`` — TS primitive
#   (``"bool"`` renders as ``boolean``).
# * ``None`` — TS ``null``.
# * ``tuple`` ``(X, "?")`` — marks the dict-value field optional.
# * ``tuple`` of ≥2 primitive names — a primitive union, rendered unquoted
#   (``("string", "number")`` → ``string | number``). Any other tuple is a
#   *literal* union, its members quoted (``("base", "overlay")`` →
#   ``"base" | "overlay"``). A one-element tuple is always a literal, so
#   ``("string",)`` stays ``"string"`` rather than becoming a bare ``string``.
# * ``list`` — array of the item's type (``[X]`` is ``X[]``).
# * ``dict`` — either an object with named identifier keys, or
#   ``Record<string, V>`` when the sole key is ``"*"``. Mixing ``"*"`` with
#   named keys is an error.
#
# The descriptor is dumped to JSON as-is: tuples become lists, so the JS
# generator disambiguates by content — an all-primitive-name list is a
# primitive union, any other all-string list a literal union, and a list
# holding a non-string an array.

_TS_PRIMITIVE_NAMES = {"string", "number", "bool", "null"}


def _validate_shape(x: Any, path: str = "", in_dict_value: bool = False) -> None:
    """Recursively validate a shape descriptor, failing loudly on bad inputs."""
    if x is None:
        return
    if isinstance(x, str):
        if x not in _TS_PRIMITIVE_NAMES:
            raise ValueError(
                f"shape at {path}: unknown primitive {x!r} — "
                f"expected one of {sorted(_TS_PRIMITIVE_NAMES)}"
            )
        return
    if isinstance(x, tuple):
        if len(x) == 2 and x[1] == "?":
            if not in_dict_value:
                raise ValueError(
                    f"shape at {path}: optional marker (X, '?') is only "
                    "valid as a dict value"
                )
            _validate_shape(x[0], f"{path}[0]")
            return
        # Otherwise: a union of strings. Primitive names render unquoted
        # ("string", "number" → string | number); everything else quoted. That
        # split is content-based and belongs to the JS renderer — the validator
        # cannot tell the two apart either, so it accepts any string tuple.
        for v in x:
            if not isinstance(v, str):
                raise ValueError(
                    f"shape at {path}: union elements must be strings, got {v!r}"
                )
        return
    if isinstance(x, list):
        if not x:
            raise ValueError(f"shape at {path}: empty array is not a valid shape")
        for i, v in enumerate(x):
            _validate_shape(v, f"{path}[{i}]")
        return
    if isinstance(x, dict):
        if "*" in x:
            if len(x) != 1:
                raise ValueError(
                    f"shape at {path}: '*' key cannot be mixed with named "
                    f"keys; got {list(x.keys())!r}"
                )
            _validate_shape(x["*"], f"{path}.*")
            return
        for k, v in x.items():
            if not isinstance(k, str) or not k.isidentifier():
                raise ValueError(
                    f"shape at {path}: key {k!r} is not a valid JS identifier"
                )
            _validate_shape(v, f"{path}.{k}", in_dict_value=True)
        return
    raise ValueError(f"shape at {path}: unknown shape type {type(x).__name__}")


@dataclass(frozen=True)
class FieldSpec:
    """Declarative spec for one CONFIG field.

    Attributes
    ----------
    ts
        Base type tag. One of :data:`_SUPPORTED_TAGS`, or ``"union"`` — in
        the union case, :attr:`values` must be set and renders as
        ``"a" | "b" | "c"``.

    optional
        Field may be absent at runtime (JSON `undefined`). Renders ``?`` in
        TS. All runtime_only fields are optional by construction.

    nullable
        Field may be JSON ``null`` in addition to its base type. Renders
        ``X | null`` in TS.

    values
        For ``ts="union"``, the tuple of string literal values.

    item
        For array tags, the item type tag (rarely used; most arrays are
        ``array_string``). Kept for extensibility; unused today.

    runtime_only
        JS sets this field at runtime; Python never emits it. Excluded from
        ``BaseControl._config_fields``; declared in TS and vitest fixture.

    dynamic
        Python emits this field at render time via ``_extra_config`` (not a
        static ``_config_fields`` key). Excluded from ``_config_fields`` but
        included in the TS type and vitest fixture.

    default
        JSON-serializable default used by the vitest fixture. Must be a
        value a Python dict can hold (str, int, float, bool, list, dict,
        or None). ``None`` is a *real* default and is serialized as JSON
        ``null``; :data:`_UNSET` (the dataclass default) means "no default
        declared — omit from fixture" (used for fields whose default is a
        runtime decision, e.g. ``locale_tables``).

    note
        Human-readable note, rendered into the generated TS: a short
        single-line note becomes a trailing ``//`` comment on the field,
        a longer or multi-line one becomes a ``/** */`` block above it.
        Empty means no comment.

    shape
        Optional shape descriptor for a complex type. When set,
        :attr:`name` is also required — the generator emits the type as a
        named alias (``export type <name> = <shape>;``) and this field's
        TS type renders as the name. See :func:`_validate_shape` for the
        descriptor grammar. A shape without a name is a construction error
        because there is no emitting target.

        Never set this on a :class:`FieldSpec` attached to an annotation: a
        descriptor is unhashable, and ``Annotated`` metadata is hashed by
        ``get_type_hints()`` on Python 3.10, so importing such a module
        raises ``TypeError`` there. Static fields declare their descriptor as
        a class attribute, ``_<name>_shape``; only specs the framework builds
        itself (dynamic fields) carry it here.

    name
        Name of a generated type alias in ``config-schema.ts``. Requires a
        shape descriptor for object/array types — the ``_<name>_shape`` class
        attribute for a static field, or :attr:`shape` for a spec the
        framework builds — or ``ts="union"`` + :attr:`values` for literal
        unions (the only shape-free case, e.g. ``NumberStyle``). Any other
        tag value with a name fails validation: the alias cannot be rendered
        without a descriptor.
    """

    ts: str = ""
    optional: bool = False
    nullable: bool = False
    values: tuple[str, ...] | None = None
    item: str | None = None
    runtime_only: bool = False
    dynamic: bool = False
    default: Any = _UNSET
    note: str = ""
    shape: Any = None
    name: str | None = None

    def __post_init__(self) -> None:
        if self.shape is not None:
            # Shape-driven type: the rendered type comes from the alias
            # name, not the base tag. Validate the shape and skip the
            # tag-based checks below — a shape-driven FieldSpec may carry
            # a ``ts`` that is not in _SUPPORTED_TAGS (e.g. the alias name
            # itself), which is fine because render_ts_type renders by
            # name.
            if not self.name:
                raise ValueError(
                    "FieldSpec.shape requires FieldSpec.name to name the "
                    "generated alias — a shape without a name has no "
                    "emitting target"
                )
            _validate_shape(self.shape, self.name)
        elif self.name is not None and self.ts != "union":
            # A named non-union type names its alias in both ``ts`` and
            # ``name`` (e.g. ``ts="ProviderConfig", name="ProviderConfig"``).
            # render_ts_type renders ``name``, so ``ts`` is a naming
            # declaration rather than a render instruction and is not checked
            # against _SUPPORTED_TAGS. Its descriptor arrives as a class
            # attribute (see derive_schema), which is why this branch — unlike
            # the shape-driven one — carries no shape. A tag typo is still
            # caught at dump time by verify_tags.
            pass
        elif self.ts == "union":
            if not self.values:
                raise ValueError(f"FieldSpec(ts='union') requires values, got None")
        elif not self.ts and not self.values:
            # A metadata-only FieldSpec (note, nullable, …) carries no tag.
            # The tag is decided by the reflector; ``ts=""`` means "no
            # override", which is distinct from a typo and must not raise
            # here — an empty tag is not in _SUPPORTED_TAGS by design.
            # ``name`` without ``shape`` is validated after reflection
            # (see ``_resolve_tag``), because the reflected ``ts``/``values``
            # are not yet known at construction time.
            pass
        elif self.ts not in _SUPPORTED_TAGS:
            raise ValueError(
                f"FieldSpec ts={self.ts!r} is not a supported tag; "
                f"valid: {sorted(set(_SUPPORTED_TAGS) | {'union'})}"
            )
        if self.runtime_only and not self.optional:
            # A field Python never emits can only be present at runtime;
            # it is therefore always optional in TS.
            raise ValueError(
                f"runtime_only field must be optional (was optional={self.optional})"
            )
        if self.dynamic and self.runtime_only:
            raise ValueError(
                "dynamic and runtime_only are mutually exclusive — a field is "
                "either emitted by Python (static or dynamic) or set by JS."
            )


ControlSchema = dict[str, FieldSpec]


def render_ts_type(spec: FieldSpec) -> str:
    """Render the TS type for one field spec.

    Combines the base tag with the nullable suffix. Raises on unknown tags
    so a typo in a schema entry fails at dump time rather than silently
    emitting a bogus type into the TS surface.

    When :attr:`FieldSpec.name` is set — either with :attr:`FieldSpec.shape`
    for a complex type or with ``ts="union"`` + :attr:`FieldSpec.values` for
    a literal union — the rendered base type is the alias name; the
    generator emits the alias definition at the top of ``config-schema.ts``.
    """
    if spec.name is not None:
        # Named type — render as the alias name; the generator emits the
        # definition elsewhere. __post_init__ + _resolve_tag guarantee the
        # descriptor (shape or union+values) is present.
        base = spec.name
    elif spec.ts == "union":
        # __post_init__ guarantees values for union; assert so mypy narrows.
        assert spec.values is not None
        base = " | ".join(f'"{v}"' for v in spec.values)
    elif spec.ts in _TS_PRIMITIVES:
        base = _TS_PRIMITIVES[spec.ts]
    elif spec.ts in _TS_OBJECTS:
        base = _TS_OBJECTS[spec.ts]
    else:
        raise ValueError(f"unknown FieldSpec.ts={spec.ts!r}")
    if spec.nullable:
        return f"{base} | null"
    return base


def verify_tags(tags: set[str], named_types: set[str]) -> None:
    """Fail loud when a tag is not a supported primitive/base-object, a
    union, the special ``string | ProviderConfig`` case, an imported name,
    or a generated named type.

    ``named_types`` are the :attr:`FieldSpec.name` values across the schema —
    types the generator emits as aliases. Any tag not in
    :data:`_SUPPORTED_TAGS` (which covers primitives, base objects,
    ``ControlPosition``, and the ``string | ProviderConfig`` special case)
    must be a named type; otherwise it is a typo or a rename that landed on
    one side only.
    """
    bad = sorted(
        t for t in tags if t not in _SUPPORTED_TAGS | {"union"} and t not in named_types
    )
    if bad:
        raise ValueError(
            f"tags render to a type name that config-schema.ts does not "
            f"declare: {bad} — add to IMPORTS (external import), "
            f"_TS_OBJECTS (inline construct), or declare as a FieldSpec.name "
            f"(generated alias)."
        )


# ── Shared (BaseControl) fields ──────────────────────────────────────────
# Emitted by every control via ``BaseControl._build_config`` /
# ``_config_block``. Not part of any control's ``_config_fields`` (they are
# the base's job), but part of the CONFIG contract every control sees.

SHARED: ControlSchema = {
    "name": FieldSpec("string", note="Control class name (Python self._name)."),
    "position": FieldSpec(
        "ControlPosition", optional=True, note="Leaflet control position."
    ),
    "locale_tables": FieldSpec(
        "object_nested",
        optional=True,
        note="Locale tables written by BaseControl._config_block.",
    ),
    "locale_code": FieldSpec(
        "string", optional=True, note="Resolved locale code (empty when unset)."
    ),
}

# ── Runtime-only fields (JS declares but Python never emits) ─────────────
# Currently both are declared in global.d.ts but never read from CONFIG by
# production JS — they are dead declarations kept for forward compatibility.
# Marking them here means the schema is a complete contract surface and the
# vitest fixture knows they can appear on CONFIG without Python emitting them.

RUNTIME_ONLY: ControlSchema = {
    "field": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Annotation field name (JS reads per-layer config, not CONFIG).",
    ),
    "background": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Export background color (currently declared but unread).",
    ),
}


# ── Reflection ─────────────────────────────────────────────────────────────
# A control's ``__init__`` signature *is* its schema. These tables translate
# the annotation of each parameter into a TS tag; everything they cannot
# decide is resolved by a ``FieldSpec(...)`` metadata attached to the type
# alias it is declared with (see ``foliplus/_typing.py``).

# Bare Python type → TS tag, for annotations the reflector can decide alone.
_PRIMITIVES: dict[type, str] = {
    str: "string",
    bool: "bool",
    int: "number",
    float: "number",
}
_ARRAY_TAGS: dict[tuple[type, ...], str] = {
    (str,): "array_string",
    (Any,): "array_unknown",
}
_DICT_TAGS: dict[tuple[type, ...], str] = {
    (Any, Any): "object",
    (str, Any): "object",
    (str, str): "object_string",
    (str, dict): "object_nested",
}

# ``BaseControl.__init__`` parameters that are the base class's job. A
# subclass that redeclares one in its own signature does not export it as a
# CONFIG field — it is already covered by :data:`SHARED`.
_SHARED_PARAMS: frozenset[str] = frozenset({"position", "locale"})


def _field_spec_in(*args: Any) -> FieldSpec | None:
    """Return the ``FieldSpec`` among ``Annotated`` metadata, or ``None``.

    ``Annotated[T, Bound(...), FieldSpec(...)]`` carries both channels:
    ``Bound`` is consumed by ``@validate`` at call time, ``FieldSpec`` here
    at schema-derivation time. Anything else (e.g. ``Annotated[int, 3]``) is
    neither and is ignored by both.
    """
    for item in args:
        if isinstance(item, FieldSpec):
            return item
    return None


def _evaluate(arg: Any) -> Any:
    """Resolve one ``Union`` arm that may still be a string.

    With `from __future__ import annotations` the arm of a spelled-out union
    (``list[str] | None``) can reach the reflector as the string ``"None"``
    rather than the type. Resolve it against the module's globals so a
    nullable union is recognised the same way whether it is spelled
    ``X | None`` or ``Optional[X]``.
    """
    if not isinstance(arg, str):
        return arg
    if arg == "None":
        return type(None)
    return eval(arg, globals())


def _is_nullable(hint: Any) -> bool:
    """Whether ``hint`` admits JSON ``null`` at its outermost level.

    Strips ``Annotated`` first: a tag override names the type, it does not
    license dropping the null. ``Annotated[ProviderConfig | None, FieldSpec(
    ts="object")]`` is still nullable.
    """
    origin = get_origin(hint)
    if origin is Annotated:
        return _is_nullable(get_args(hint)[0])
    if origin not in (Union, UnionType):
        return False
    arms = [_evaluate(a) for a in get_args(hint)]
    non_null = [a for a in arms if a is not type(None)]
    return len(non_null) == 1 and len(non_null) != len(arms)


def _resolve_tag(
    hint: Any, meta: FieldSpec | None
) -> tuple[str, tuple[str, ...] | None, bool, FieldSpec | None]:
    """Resolve one annotation to ``(tag, values, nullable, spec)``.

    ``spec`` is the author's ``FieldSpec`` metadata (or ``None``):
    :func:`derive_schema` reads ``optional`` and ``note`` from it. ``ts``,
    ``values`` and ``nullable`` are the reflector's own decision, reported
    separately so the caller can see what was decided and from where.

    Layers, in order of authority:

    1. An explicit ``FieldSpec(ts=...)`` — an override the author wrote
       because the automatic mapping cannot decide (a ``Literal`` that is
       really ``NumberStyle``, a ``str | dict`` union that is really
       ``ProviderConfig``, …).
    2. ``X | None`` — a nullable variant of whatever ``X`` resolves to.
    3. Bare Python type, ``Literal``, ``list[X]``, ``dict[K, V]``.

    ``peeled`` distinguishes a real ``Literal`` from a type alias that
    happens to be a ``Literal``: a bare ``Literal`` is a union, but a
    ``Literal`` wrapped in ``Annotated`` with a ``FieldSpec`` is the alias.
    """
    origin = get_origin(hint)
    # Peel Annotated for the base type whether or not it carries a FieldSpec:
    # ``Annotated[float, Bound(0.0, 1.0)]`` validates at call time and has
    # nothing to say about the TS tag, so ``base`` must reach ``float``.
    args = get_args(hint) if origin is Annotated else ()
    base = args[0] if args else hint
    inner_meta = _field_spec_in(*args[1:]) if args else None
    # A layer that carries no FieldSpec keeps the one passed down by an outer
    # layer: `Annotated[PositiveInt | None, FieldSpec(note=...)]` peels to
    # `Annotated[int, Bound(...)] | None`, whose Bound is not a FieldSpec, and
    # the note must survive that hop.
    meta = inner_meta or meta
    peeled = meta is not None
    if meta is not None and meta.shape is not None:
        # A shape descriptor is unhashable, and Annotated metadata is hashed
        # by get_type_hints() on Python 3.10, so importing such a module
        # raises TypeError there. Check this before deciding the tag: a shape
        # field usually has no ts override, so tag resolution would fail on
        # the dict base type first with a message about the wrong thing.
        raise ValueError(_SHAPE_IN_ANNOTATION_ERROR)

    if meta is not None and meta.ts:
        # The author named the type; nullability still comes from the
        # annotation, not from the override.
        return meta.ts, meta.values, _is_nullable(hint) or meta.nullable, meta

    if origin is Annotated:
        # No tag override, so the type to render is the annotated base. It may
        # itself be a union or another Annotated (PositiveInt is
        # Annotated[int, Bound(...)]), so recurse rather than re-implementing
        # the mapping below; the meta carries note and optional through.
        tag, values, nullable, inner_meta = _resolve_tag(base, meta)
        return tag, values, nullable, meta or inner_meta

    if origin in (Union, UnionType):
        arms = [_evaluate(a) for a in get_args(hint)]
        non_null = [a for a in arms if a is not type(None)]
        nullable = len(non_null) != len(arms)
        if len(non_null) == 1:
            # A FieldSpec may sit inside the non-null arm rather than on the
            # union: Python 3.10's get_type_hints wraps a `= None` default in
            # Optional[...], so `Annotated[dict, FieldSpec(...)]` reaches
            # here as `Optional[Annotated[dict, FieldSpec(...)]}`. Taking the
            # arm's spec back is what keeps the author's ts/name/note alive
            # there — a spec passed down from an outer layer still wins.
            tag, values, inner_nullable, inner_meta = _resolve_tag(non_null[0], meta)
            return tag, values, nullable or inner_nullable, meta or inner_meta
        # A union of two unrelated arms is not a JSON shape: the author must
        # name it. ProviderConfig's `str | dict` reaches here as
        # `str | TypedDict` and carries FieldSpec(ts=...) for exactly this.
        raise ValueError(
            f"cannot map union annotation {hint!r} to a TS tag — add "
            "FieldSpec(ts=...) to name the union"
        )

    if origin is Literal:
        if not peeled:
            return "union", tuple(str(v) for v in get_args(hint)), False, meta
        # A peeled Literal (wrapped in Annotated with a FieldSpec) is an
        # alias: the reflected tag is "union" with the Literal's values, and
        # the author's FieldSpec names the alias via ``name`` so the
        # generator emits it. A ``ts`` override on a Literal returns at the
        # meta.ts check above, because ts names the type outright.
        values = tuple(str(v) for v in get_args(hint))
        nullable = _is_nullable(hint)
        if meta is not None and meta.name is not None:
            return "union", values, nullable or meta.nullable, meta
        raise ValueError(
            "a Literal alias needs FieldSpec(name=...) to name its TS type; "
            "bare Literal unions are decided automatically"
        )

    if base in _PRIMITIVES:
        return _PRIMITIVES[base], None, False, None

    if get_origin(base) is list:
        return _ARRAY_TAGS.get(get_args(base), "array_unknown"), None, False, None

    if get_origin(base) is dict:
        return _DICT_TAGS.get(get_args(base), "object"), None, False, None

    raise ValueError(
        f"cannot map annotation {hint!r} to a TS tag — add FieldSpec(ts=...) "
        "to the type alias it is declared with, or extend _config_schema"
    )


def _is_json_serializable(value: Any) -> bool:
    """Return ``True`` when ``value`` can be held by the vitest fixture.

    The fixture is JSON; anything else a default could be (an enum member, a
    bound method, a path) would have to be serialized by hand, so the dump
    fails loud rather than emitting a non-JSON default.
    """
    return (
        value is None
        or isinstance(value, (str, int, float, bool))
        or (isinstance(value, list) and all(_is_json_serializable(v) for v in value))
        or (
            isinstance(value, dict)
            and all(_is_json_serializable(v) for v in value.values())
        )
    )


def derive_schema(cls: type[BaseControl]) -> ControlSchema:
    """Reflect ``cls.__init__`` into a :class:`ControlSchema`.

    Signature order becomes schema order, and schema order becomes
    ``_config_fields`` order, so a new parameter appended to a signature
    appends a CONFIG key — moving a parameter moves the key. Parameters
    inherited from ``BaseControl.__init__`` (``position``, ``locale``) are
    skipped: they are the base's job, already covered by :data:`SHARED`.

    Defaults must be JSON-serializable — the fixture is generated from them.
    A parameter whose default is a runtime decision (nothing the author can
    write in a signature) raises; such a field is either dynamic
    (:attr:`BaseControl._dynamic_fields`) or should not be a CONFIG field at
    all.
    """
    init = cls.__init__
    sig = inspect.signature(init)
    try:
        hints = get_type_hints(init, include_extras=True)
    except TypeError as exc:
        # Python 3.10 wraps a `= None` default in Optional[...], which
        # deduplicates the arms by hashing them — and Annotated metadata is
        # hashed too, so a FieldSpec carrying an unhashable shape descriptor
        # aborts here with a bare "unhashable type" that names no fix. Raise
        # the same error _resolve_tag raises on 3.11+, where get_type_hints
        # does not hash and the descriptor is still reachable.
        if "unhashable" not in str(exc):
            raise
        raise ValueError(f"{cls.__name__}: {_SHAPE_IN_ANNOTATION_ERROR}") from exc
    out: ControlSchema = {}
    for name, param in sig.parameters.items():
        if name == "self" or name == "return" or name in _SHARED_PARAMS:
            continue

        hint = hints.get(name, param.annotation)
        has_default = param.default is not inspect._empty  # noqa: SLF001

        # Order matters: a missing default is a declaration error (the field
        # cannot be a CONFIG field at all), so it is reported before the
        # annotation is mapped — otherwise an author sees a tag error for a
        # parameter they did not intend to export.
        if not has_default:
            raise ValueError(
                f"{cls.__name__}.{name} has no default — a CONFIG field without a "
                "default is emitted only if JS sets it (runtime_only), which "
                "cannot be declared in a signature"
            )

        tag, values, nullable, meta = _resolve_tag(hint, None)
        # A shape descriptor is unhashable, and Annotated metadata is hashed
        # on Python 3.10 (get_type_hints), so a shape must never be attached
        # to an annotation — _resolve_tag rejects one. Named non-union types
        # carry their descriptor as a class attribute next to the field
        # declaration, ``_<name>_shape``, the same convention dynamic fields
        # use.
        shape: Any = None
        if meta is not None and meta.name is not None:
            # Only non-union named types need a descriptor: a reflected union
            # renders itself from ``values``.
            if tag != "union":
                shape_attr = f"_{name}_shape"
                shape = getattr(cls, shape_attr, None)
                if shape is None:
                    raise ValueError(
                        f"{cls.__name__}.{name} FieldSpec.name={meta.name!r} "
                        f"names a non-union type (ts={tag!r}), which needs a "
                        f"shape descriptor — set {shape_attr} on the class"
                    )
                # Validate like __post_init__ does, since the descriptor came
                # from a class attribute rather than a FieldSpec.
                _validate_shape(shape, meta.name)
        if not _is_json_serializable(param.default):
            raise ValueError(
                f"{cls.__name__}.{name} default {param.default!r} is not JSON "
                "serializable — the vitest fixture is generated from it"
            )

        # Reflection decides the tag; the author's FieldSpec decides the
        # render-time attributes. `optional` defaults to False: Python emits
        # every non-runtime, non-dynamic field, so the per-control TS interface
        # declares it required — runtime_only and dynamic carry optionality.
        # ``shape`` and ``name`` come from the author's FieldSpec and the
        # class: ``name`` is in the annotation (a plain string, so hashable),
        # ``shape`` is the ``_<name>_shape`` class attribute (see above). The
        # reflector cannot infer either from a Python annotation.
        spec = FieldSpec(
            ts=tag,
            values=values,
            nullable=nullable,
            optional=meta.optional if meta else False,
            default=param.default,
            note=meta.note if meta else "",
            shape=shape,
            name=meta.name if meta else None,
        )
        out[name] = spec

    # Dynamic fields are collected at render time (LayerControl's ``data``),
    # so they are not parameters — the class declares them here. The TS type
    # is described by a name-and-shape pair sitting next to the field
    # declaration: ``_<name>_hint`` is the emitted alias name,
    # ``_<name>_shape`` is the descriptor that renders into that alias. Both
    # must be set; ``_hint`` alone is no longer sufficient because the shape
    # has moved from the TS surface to the schema.
    for name in getattr(cls, "_dynamic_fields", ()):
        if name in out:
            raise ValueError(
                f"{cls.__name__}.{name} is declared both in the signature and "
                "in _dynamic_fields — a dynamic field is not a parameter"
            )
        hint_attr = f"_{name}_hint"
        shape_attr = f"_{name}_shape"
        if not hasattr(cls, hint_attr):
            raise ValueError(
                f"{cls.__name__} declares {name} in _dynamic_fields but does "
                f"not set {hint_attr} — dynamic fields carry their emitted "
                "alias name next to the declaration."
            )
        if not hasattr(cls, shape_attr):
            raise ValueError(
                f"{cls.__name__} declares {name} in _dynamic_fields but does "
                f"not set {shape_attr} — dynamic fields carry their TS shape "
                "next to the declaration."
            )
        out[name] = FieldSpec(
            ts=getattr(cls, hint_attr),
            name=getattr(cls, hint_attr),
            shape=getattr(cls, shape_attr),
            dynamic=True,
            optional=True,
            default=[],
            note="Layer list collected from the parent map at render time via _extra_config.",
        )

    return out


# ── Per-control schemas ──────────────────────────────────────────────────
# Order within a control's schema is signature order — the derived
# ``_config_fields`` tuple inherits it verbatim, so a reordered signature
# reorders the exported CONFIG keys.


def config_fields(schema: ControlSchema) -> tuple[str, ...]:
    """Fields Python emits to CONFIG for one control (non-runtime, non-dynamic keys).

    Order is declaration order. Called by BaseControl's
    ``__init_subclass__``, which assigns the result to ``_config_fields`` —
    the schema is the single source and the tuple inherits this order.
    Dynamic and runtime-only fields are intentionally excluded — dynamic
    fields are emitted via ``_extra_config`` and runtime-only fields are
    JS-set.
    """
    return tuple(k for k, f in schema.items() if not f.runtime_only and not f.dynamic)


def schema_to_json() -> str:
    """Serialize the whole schema table to JSON (deterministic, sorted).

    The dumped shape is what pytest consumes as the schema source of truth,
    and what the two manual emitters (``script/build/emit-config-schema.mjs``
    and ``test/js/script/emit-config-fixture.mjs``) read when regenerating the
    committed TS artifacts. Kept stable: adding a new ``FieldSpec`` attribute
    is a schema version bump, not a silent change.

    Every tag is checked against the union of :data:`_SUPPORTED_TAGS` and the
    set of generated alias names (:func:`verify_tags`) so a tag that renders
    to a type name ``config-schema.ts`` does not declare fails here rather
    than as an unimported type in the generated TS.

    Must not touch ``sys.path`` or ``sys.modules``: in-process callers (pytest)
    already hold a live ``foliplus`` import, and re-importing the package would
    hand the reflector a second ``FieldSpec`` class — the ``isinstance`` check
    in :func:`_field_spec_in` would then stop finding the ``Annotated``
    metadata and every typed field would fail to resolve. Path pinning for
    script mode lives in ``__main__`` below.
    """
    from foliplus import BaseControl

    control_schemas = _derived_control_schemas(BaseControl)
    payload = {
        "version": 1,
        "shared": _field_dict_list(SHARED),
        "runtime_only": _field_dict_list(RUNTIME_ONLY),
        "controls": {
            name: _field_dict_list(schema) for name, schema in control_schemas
        },
    }
    verify_tags(
        collect_tags(SHARED, RUNTIME_ONLY, *(s for _, s in control_schemas)),
        collect_named_types(SHARED, RUNTIME_ONLY, *(s for _, s in control_schemas)),
    )
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _pin_package_path(
    keep: tuple[str, ...] = (),
) -> None:  # pragma: no cover - script bootstrap: runpy subprocess test
    """Force ``foliplus`` to resolve to this module's own package.

    Needed only when this file runs as a script: ``python foliplus/_config_schema.py``
    prepends the script's directory to ``sys.path``, which is stripped on import
    (it shadows stdlib ``locale``), so ``import foliplus`` would fall back to
    whatever an editable install resolves to — possibly a different checkout.
    Put the package's parent directory on ``sys.path`` first and drop any
    already-imported ``foliplus`` modules so the import picks up the siblings
    of this file.

    ``keep`` names modules to leave in ``sys.modules``: this file executing as
    a script registers itself under its package name first, so its siblings can
    import ``FieldSpec`` from it instead of loading a second copy.

    Never called from :func:`schema_to_json`: that would re-import ``foliplus``
    out from under an in-process caller and split class identity.
    """
    pkg_dir = str(Path(__file__).resolve().parent.parent)
    if pkg_dir in sys.path:
        sys.path.remove(pkg_dir)
    sys.path.insert(0, pkg_dir)
    for name in list(sys.modules):
        if name in keep:
            continue
        if name == "foliplus" or name.startswith("foliplus."):
            del sys.modules[name]
    import foliplus  # noqa: F401 -- re-import against the pinned path

    own_pkg_dir = str(Path(foliplus.__file__).resolve().parent.parent)
    if own_pkg_dir != pkg_dir:
        raise RuntimeError(
            f"foliplus resolves to {own_pkg_dir}, but this module lives in "
            f"{pkg_dir} — the editable-install path hook is overriding sys.path"
        )


def _derived_control_schemas(base: type) -> list[tuple[str, ControlSchema]]:
    """Reflect every shipped control, returning ``(name, schema)`` pairs."""
    return [
        (c.__name__, derive_schema(c))
        for c in sorted(
            (
                c
                for c in base.__subclasses__()
                if c.__module__.startswith("foliplus.")
                and not c.__name__.startswith("_")
            ),
            key=lambda c: c.__name__,
        )
    ]


def collect_tags(*schemas: ControlSchema) -> set[str]:
    """Every tag appearing in ``schemas`` (for :func:`verify_tags`).

    Empty tags (metadata-only FieldSpecs where the reflector decides the
    tag) are skipped — they are not type names and must not be checked
    against :data:`_SUPPORTED_TAGS`.
    """
    return {spec.ts for schema in schemas for spec in schema.values() if spec.ts}


def collect_named_types(*schemas: ControlSchema) -> set[str]:
    """Every generated alias name across ``schemas`` (for :func:`verify_tags`).

    ``FieldSpec.name`` values are the types the generator emits as aliases in
    ``config-schema.ts`` — the "second half" of the tag universe alongside
    primitives/base-objects/imports.
    """
    return {spec.name for schema in schemas for spec in schema.values() if spec.name}


def _field_dict_list(schema: ControlSchema) -> dict[str, dict[str, Any]]:
    """Convert one ControlSchema to a JSON-friendly dict of field dicts.

    Drops the Python-only ``item`` field the generators don't need; ``note`` is
    kept so the generated TS carries docstrings. ``shape`` and ``name`` are
    emitted when set: they carry the descriptor the generator needs to emit a
    named alias in ``config-schema.ts``, and the field's TS type renders as
    the name.
    """
    out: dict[str, dict[str, Any]] = {}
    for name, spec in schema.items():
        entry: dict[str, Any] = {
            "ts": spec.ts,
            "optional": spec.optional or spec.runtime_only,
            "nullable": spec.nullable,
            "runtime_only": spec.runtime_only,
            "dynamic": spec.dynamic,
        }
        if spec.values is not None:
            entry["values"] = list(spec.values)
        if spec.note:
            entry["note"] = spec.note
        if spec.default is not _UNSET:
            entry["default"] = spec.default
        if spec.shape is not None:
            entry["shape"] = spec.shape
        if spec.name is not None:
            entry["name"] = spec.name
        out[name] = entry
    return out


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="foliplus._config_schema",
        description="Dump the CONFIG schema as JSON for pytest and manual regeneration.",
    )
    parser.add_argument(
        "--dump",
        action="store_true",
        help="Print the schema JSON to stdout (default when --out is omitted).",
    )
    parser.add_argument(
        "--out",
        metavar="PATH",
        help="Write the schema JSON to PATH instead of stdout.",
    )
    args = parser.parse_args(argv)
    text = schema_to_json()
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    # As a script this file is not registered as foliplus._config_schema, so a
    # sibling doing `from ._config_schema import FieldSpec` would load a second
    # copy — a second FieldSpec class, which the isinstance() check in
    # _field_spec_in() would not match. Register this module first.
    sys.modules["foliplus._config_schema"] = sys.modules["__main__"]
    # sys.path[0] was this directory (stripped above), so pin the package path
    # before schema_to_json() imports foliplus.
    _pin_package_path(keep=("foliplus._config_schema",))
    raise SystemExit(_main())
