"""Single source of truth for the CONFIG contract between Python and JS.

Every foliplus control declares its configuration surface here as a
:class:`ControlSchema` mapping field names to :class:`FieldSpec` entries.
Three downstream surfaces are derived from this table:

1. ``BaseControl._config_fields`` (Python serialization side) — derived by
   ``BaseControl.__init_subclass__`` from the schema's non-runtime-only keys,
   in declaration order. No control module writes its own tuple.
2. ``foliplus/js/config-schema.ts`` (TS ``ComponentConfig`` type) — generated by
   ``script/build/emit-config-schema.mjs`` from the same dump.
3. ``test/js/config-fixture.ts`` (vitest CONFIG fixture) — generated by
   ``script/emit-config-fixture.mjs`` from the same dump.

Fields tagged ``runtime_only`` appear on the JS type and the vitest fixture
but are never emitted by Python: they are read from ``CONFIG`` at runtime by
JS code paths that Python cannot reach. The current set is ``field`` and
``background`` — both declared in ``global.d.ts`` historically and never
read by JS either, but keeping them here means the schema is a *complete*
declaration surface rather than a subset of it.

**Values are zero-impact.** Nothing in this module is consulted at render
time: ``BaseControl._build_config`` reads ``self._config_fields`` (derived
once, at class-definition time) and never touches this table. Changing a
schema entry cannot alter what ``BaseControl._config_block`` serializes —
enforced by the existing Python tests that snapshot the emitted JSON.

Usage (build tooling):

    python foliplus/_config_schema.py --dump                                    # stdout
    python foliplus/_config_schema.py --out foliplus/.build/js/config-schema.json  # file

    # Or via python -m (requires branca/folium installed):
    python -m foliplus._config_schema --dump

Schema format:

    SCHEMAS: dict[ControlName, dict[FieldName, FieldSpec]]

Each ``FieldSpec`` carries the TS type tag plus optional/nullability flags
plus the default value used by the vitest fixture.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# When run as `python foliplus/_config_schema.py`, the script's directory is prepended
# to sys.path. This shadows stdlib `locale` with `foliplus/locale` (which has
# no `normalize()`), breaking argparse's gettext import. Strip the script dir
# so stdlib modules resolve correctly. Safe: `_config_schema.py` imports no foliplus
# siblings, so it does not need the package on sys.path.
_script_dir = str(Path(__file__).resolve().parent)
if _script_dir in sys.path:
    sys.path.remove(_script_dir)

# TS type tags supported. Kept small — fields are flat, no nested object
# shapes beyond `Record<string, unknown>` and array-of-string. Add a new tag
# only when a real control needs it; the generator refuses unknown tags so a
# typo fails the build rather than emitting a bogus type.
_TS_PRIMITIVES: dict[str, str] = {
    "bool": "boolean",
    "number": "number",
    "string": "string",
    "any": "unknown",
    "null": "null",
}
_TS_OBJECTS: dict[str, str] = {
    "object": "Record<string, unknown>",
    "object_string": "Record<string, string>",
    "object_nested": "Record<string, Record<string, string>>",
    "array_string": "string[]",
    "array_unknown": "unknown[]",
    # SearchControl's `provider` is `str | dict` — the string is a built-in
    # provider id, the dict is a custom ProviderConfig. Kept as a special tag
    # so the emitted TS reads `string | ProviderConfig` (typed via ProviderConfig
    # in global.d.ts) rather than the generic `Record<string, unknown>`.
    "provider": "string | ProviderConfig",
    # `locale_tables` is the shared locale table shape; imported from
    # #common/locale.js in the generated TS.
    "locale_tables": "LocaleTables",
    # `number_style` is the HeatmapControl label_format tag; imported from
    # #common/format.js.
    "number_style": "NumberStyle",
    # LayerControl's dynamic `data` field — the layer list collected from the
    # parent map at render time. Shape is an array of small label descriptors.
    "layer_data": 'Array<{ name: string; id: string; group: "base" | "overlay" }>',
    # `position` is the Leaflet control position — a string literal union.
    # Imported from Leaflet in the generated TS.
    "control_position": "ControlPosition",
}
_SUPPORTED_TAGS = set(_TS_PRIMITIVES) | set(_TS_OBJECTS)


# Sentinel distinguishing "no default declared" from an explicit null/None
# default. `default: Any = None` cannot carry that distinction — a field whose
# real default is None (e.g. SearchControl.provider_config) would be treated
# as "no default" and dropped from the dump. Anything JSON-serializable is a
# legal default, including None.
_UNSET = object()


@dataclass(frozen=True)
class FieldSpec:
    """Declarative spec for one CONFIG field.

    Attributes
    ----------
    ts
        Base type tag. One of :data:`_SUPPORTED_TAGS`, or ``"union"`` — in
        the union case, :attr:`values` must be set and renders as
        ``"a" | "b" | "c"``.
    optional
        Field may be absent at runtime (JSON `undefined`). Renders ``?`` in
        TS. All runtime_only fields are optional by construction.
    nullable
        Field may be JSON ``null`` in addition to its base type. Renders
        ``X | null`` in TS.
    values
        For ``ts="union"``, the tuple of string literal values.
    item
        For array tags, the item type tag (rarely used; most arrays are
        ``array_string``). Kept for extensibility; unused today.
    runtime_only
        JS sets this field at runtime; Python never emits it. Excluded from
        ``BaseControl._config_fields``; declared in TS and vitest fixture.
    dynamic
        Python emits this field at render time via ``_extra_config`` (not a
        static ``_config_fields`` key). Excluded from ``_config_fields`` but
        included in the TS type and vitest fixture.
    default
        JSON-serializable default used by the vitest fixture. Must be a
        value a Python dict can hold (str, int, float, bool, list, dict,
        or None). ``None`` is a *real* default and is serialized as JSON
        ``null``; :data:`_UNSET` (the dataclass default) means "no default
        declared — omit from fixture" (used for fields whose default is a
        runtime decision, e.g. ``locale_tables``).
    note
        Human-readable note, rendered into the generated TS: a short
        single-line note becomes a trailing ``//`` comment on the field,
        a longer or multi-line one becomes a ``/** */`` block above it.
        Empty means no comment.
    """

    ts: str
    optional: bool = False
    nullable: bool = False
    values: tuple[str, ...] | None = None
    item: str | None = None
    runtime_only: bool = False
    dynamic: bool = False
    default: Any = _UNSET
    note: str = ""

    def __post_init__(self) -> None:
        if self.ts == "union":
            if not self.values:
                raise ValueError(f"FieldSpec(ts='union') requires values, got None")
        elif self.ts not in _SUPPORTED_TAGS:
            raise ValueError(
                f"FieldSpec ts={self.ts!r} is not a supported tag; "
                f"valid: {sorted(set(_SUPPORTED_TAGS) | {'union'})}"
            )
        if self.runtime_only and not self.optional:
            # A field Python never emits can only be present at runtime;
            # it is therefore always optional in TS.
            raise ValueError(
                f"runtime_only field must be optional (was optional={self.optional})"
            )
        if self.dynamic and self.runtime_only:
            raise ValueError(
                "dynamic and runtime_only are mutually exclusive — a field is "
                "either emitted by Python (static or dynamic) or set by JS."
            )


ControlSchema = dict[str, FieldSpec]


def render_ts_type(spec: FieldSpec) -> str:
    """Render the TS type for one field spec.

    Combines the base tag with the nullable suffix. Raises on unknown tags
    so a typo in a schema entry fails at dump time rather than silently
    emitting a bogus type into the TS surface.
    """
    if spec.ts == "union":
        # __post_init__ guarantees values for union; assert so mypy narrows.
        assert spec.values is not None
        base = " | ".join(f'"{v}"' for v in spec.values)
    elif spec.ts in _TS_PRIMITIVES:
        base = _TS_PRIMITIVES[spec.ts]
    elif spec.ts in _TS_OBJECTS:
        base = _TS_OBJECTS[spec.ts]
    else:
        raise ValueError(f"unknown FieldSpec.ts={spec.ts!r}")
    if spec.nullable:
        return f"{base} | null"
    return base


# ── Shared (BaseControl) fields ──────────────────────────────────────────
# Emitted by every control via ``BaseControl._build_config`` /
# ``_config_block``. Not part of any control's ``_config_fields`` (they are
# the base's job), but part of the CONFIG contract every control sees.

SHARED: ControlSchema = {
    "name": FieldSpec("string", note="Control class name (Python self._name)."),
    "position": FieldSpec(
        "control_position", optional=True, note="Leaflet control position."
    ),
    "locale_tables": FieldSpec(
        "locale_tables",
        optional=True,
        note="Locale tables written by BaseControl._config_block.",
    ),
    "locale_code": FieldSpec(
        "string", optional=True, note="Resolved locale code (empty when unset)."
    ),
}

# ── Runtime-only fields (JS declares but Python never emits) ─────────────
# Currently both are declared in global.d.ts but never read from CONFIG by
# production JS — they are dead declarations kept for forward compatibility.
# Marking them here means the schema is a complete contract surface and the
# vitest fixture knows they can appear on CONFIG without Python emitting them.

RUNTIME_ONLY: ControlSchema = {
    "field": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Annotation field name (JS reads per-layer config, not CONFIG).",
    ),
    "background": FieldSpec(
        "string",
        optional=True,
        runtime_only=True,
        note="Export background color (currently declared but unread).",
    ),
}


# ── Per-control schemas ──────────────────────────────────────────────────
# Order within a control's schema is declaration order — the derived
# ``_config_fields`` tuple inherits it verbatim, so a reordered schema
# entry reorders the exported CONFIG keys.

_FULLSCREEN: ControlSchema = {
    "hide_self": FieldSpec("bool", default=True),
    "hide_others": FieldSpec("bool", default=True),
}

_SCALE: ControlSchema = {
    "show_zoom": FieldSpec("bool", default=True),
}

_LOCATE: ControlSchema = {
    "zoom": FieldSpec("number", default=15),
}

_LAYER: ControlSchema = {
    "label_collide": FieldSpec("bool", default=True),
    "collapse_on_outside": FieldSpec("bool", default=False),
    "data": FieldSpec(
        "layer_data",
        dynamic=True,
        optional=True,
        default=[],
        note="Layer list collected from the parent map at render time via _extra_config.",
    ),
}

_MEASURE: ControlSchema = {
    "show_bearing": FieldSpec("bool", default=True),
    "label_show": FieldSpec("bool", default=True),
    "label_collide": FieldSpec("bool", default=True),
    "show_live_coords": FieldSpec("bool", default=True),
    "filename": FieldSpec("string", default="measurements"),
    "export_format": FieldSpec(
        "union",
        values=("geojson", "csv"),
        default="geojson",
        note="MeasureControl export format.",
    ),
    "collapse_on_outside": FieldSpec("bool", default=True),
}

_SEARCH: ControlSchema = {
    "mode": FieldSpec(
        "union",
        values=("coord", "addr"),
        default="coord",
        note="Default search mode on first open.",
    ),
    "zoom": FieldSpec("number", default=15),
    "provider": FieldSpec(
        "provider",
        default="nominatim",
        note="Built-in provider id or a custom ProviderConfig dict.",
    ),
    "provider_config": FieldSpec(
        "object",
        nullable=True,
        optional=True,
        default=None,
        note="Overrides for a built-in provider; only valid with a string provider.",
    ),
    "collapse_on_outside": FieldSpec("bool", default=True),
}

_HEATMAP: ControlSchema = {
    "color_scheme": FieldSpec("string", default="Reds"),
    "method": FieldSpec(
        "union",
        values=("jenks", "quantile", "equal", "heads"),
        default="jenks",
    ),
    "n_classes": FieldSpec("number", default=6),
    "agg": FieldSpec(
        "union",
        values=("count", "sum", "avg", "min", "max"),
        default="count",
    ),
    "schemes": FieldSpec(
        "array_string",
        optional=True,
        default=["Blues", "Greens", "Reds", "Oranges", "Purples", "YlOrRd", "Viridis"],
        note="Available color scheme names.",
    ),
    "border_weight": FieldSpec("number", default=1.5),
    "border_color": FieldSpec("string", default="#333333"),
    "fill_opacity": FieldSpec("number", default=0.7),
    "border_opacity": FieldSpec("number", default=0.9),
    "label_show": FieldSpec("bool", default=True),
    "label_color": FieldSpec("string", default="#fff"),
    "label_size": FieldSpec("number", default=11),
    "label_format": FieldSpec(
        "number_style",
        default="auto",
        note="Number format for hexagon value labels.",
    ),
    "collapse_on_outside": FieldSpec("bool", default=True),
}

_EXPORT: ControlSchema = {
    "filename": FieldSpec("string", default="map"),
    "format": FieldSpec(
        "union",
        values=("png", "jpeg", "webp", "geotiff"),
        default="png",
    ),
    "quality": FieldSpec("number", default=0.92),
    "scale": FieldSpec("number", default=2.0),
    "max_pixels": FieldSpec(
        "number",
        nullable=True,
        default=10_240_000,
        note="Null disables the pixel limit.",
    ),
    "timeout": FieldSpec("number", default=7500),
}


# Registry keyed by Python control class name. ``BaseControl`` subclasses
# without an entry here are left untouched by the derivation: they keep
# whatever ``_config_fields`` / ``default_js`` they (or a base class)
# declared. The test suite requires every shipped control to have an entry,
# so an unregistered one never ships silently.
SCHEMAS: dict[str, ControlSchema] = {
    "FullscreenControl": _FULLSCREEN,
    "ScaleControl": _SCALE,
    "LocateControl": _LOCATE,
    "LayerControl": _LAYER,
    "MeasureControl": _MEASURE,
    "SearchControl": _SEARCH,
    "HeatmapControl": _HEATMAP,
    "ExportControl": _EXPORT,
}


def config_fields(schema: ControlSchema) -> tuple[str, ...]:
    """Fields Python emits to CONFIG for one control (non-runtime, non-dynamic keys).

    Order is declaration order. Called by BaseControl's
    ``__init_subclass__``, which assigns the result to ``_config_fields`` —
    the schema is the single source and the tuple inherits this order.
    Dynamic and runtime-only fields are intentionally excluded — dynamic
    fields are emitted via ``_extra_config`` and runtime-only fields are
    JS-set.
    """
    return tuple(k for k, f in schema.items() if not f.runtime_only and not f.dynamic)


def schema_to_json() -> str:
    """Serialize the whole schema table to JSON (deterministic, sorted).

    The dumped shape is what ``script/build/emit-config-schema.mjs`` and
    ``script/emit-config-fixture.mjs`` consume. Kept stable: adding a new
    ``FieldSpec`` attribute is a schema version bump, not a silent change.
    """
    payload = {
        "version": 1,
        "shared": _field_dict_list(SHARED),
        "runtime_only": _field_dict_list(RUNTIME_ONLY),
        "controls": {
            name: _field_dict_list(schema) for name, schema in sorted(SCHEMAS.items())
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _field_dict_list(schema: ControlSchema) -> dict[str, dict[str, Any]]:
    """Convert one ControlSchema to a JSON-friendly dict of field dicts.

    Drops Python-only fields (``item``, ``note``) that the generators don't
    need — ``note`` is still kept so the generated TS carries docstrings.
    """
    out: dict[str, dict[str, Any]] = {}
    for name, spec in schema.items():
        entry: dict[str, Any] = {
            "ts": spec.ts,
            "optional": spec.optional or spec.runtime_only,
            "nullable": spec.nullable,
            "runtime_only": spec.runtime_only,
            "dynamic": spec.dynamic,
        }
        if spec.values is not None:
            entry["values"] = list(spec.values)
        if spec.note:
            entry["note"] = spec.note
        if spec.default is not _UNSET:
            entry["default"] = spec.default
        out[name] = entry
    return out


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="foliplus._config_schema",
        description="Dump the CONFIG schema as JSON for build tooling.",
    )
    parser.add_argument(
        "--dump",
        action="store_true",
        help="Print the schema JSON to stdout (default when --out is omitted).",
    )
    parser.add_argument(
        "--out",
        metavar="PATH",
        help="Write the schema JSON to PATH instead of stdout.",
    )
    args = parser.parse_args(argv)
    text = schema_to_json()
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
