import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { afterEach, describe, expect, it } from "vitest";
import {
  buildConfFixture,
  main,
  resolveSchemaJson,
} from "#script/gen-conf-fixture.mjs";

// Shape matches foliplus/_schema.py's dump. Two controls share the `filename`
// key with different defaults — the regression the per-control grouping fixes.
// `buildControlDefaults` only reads `field.default`, so the branch-covering
// table below uses a compact spec.
const field = (ts: string, value: unknown) => ({ ts, default: value });
const schema = {
  version: 1,
  shared: {
    name: {
      ts: "string",
      optional: false,
      nullable: false,
      runtime_only: false,
      dynamic: false,
    },
  },
  runtime_only: {},
  controls: {
    ExportControl: {
      filename: {
        ts: "string",
        optional: false,
        nullable: false,
        runtime_only: false,
        dynamic: false,
        default: "map",
      },
    },
    MeasureControl: {
      filename: {
        ts: "string",
        optional: false,
        nullable: false,
        runtime_only: false,
        dynamic: false,
        default: "measurements",
      },
    },
    SearchControl: {
      mode: {
        ts: "union",
        optional: false,
        nullable: false,
        runtime_only: false,
        dynamic: false,
        values: ["coord", "addr"],
        default: "coord",
      },
      provider_config: {
        ts: "object",
        optional: true,
        nullable: true,
        runtime_only: false,
        dynamic: false,
        default: null,
      },
    },
    // Exercises formatValue's remaining value shapes: number, boolean, empty
    // array, non-empty array, and a nested object. Names are synthetic — the
    // real schema dump never declares an empty array or object default.
    DemoControl: {
      n_classes: field("number", 6),
      label_show: field("bool", true),
      groups: field("array_string", []),
      schemes: field("array_string", ["Blues", "Reds"]),
      label_format: field("object", { digits: 2 }),
    },
  },
};

describe("buildConfFixture", () => {
  it("groups defaults per control — no cross-control collision", async () => {
    const text = await buildConfFixture(schema);
    // Both filename defaults survive; the earlier one no longer overwrites.
    expect(text).toMatch(/ExportControl: \{\n    filename: "map"/);
    expect(text).toMatch(/MeasureControl: \{\n    filename: "measurements"/);
  });

  it("serializes explicit null defaults as null", async () => {
    const text = await buildConfFixture(schema);
    expect(text).toMatch(/provider_config: null,/);
  });

  it("makeConf takes controlName and merges overrides last", async () => {
    const text = await buildConfFixture(schema);
    expect(text).toContain("function makeConf(");
    expect(text).toContain("controlName: string,");
    expect(text).toContain("overrides?: Partial<ComponentConfig>,");
    expect(text).toMatch(/name: controlName,/);
    expect(text).toContain("...CONF_DEFAULTS[controlName],");
    expect(text).toContain("...overrides,");
  });

  it("exports makeConf via a bottom aggregate block", async () => {
    const text = await buildConfFixture(schema);
    const tail = text.slice(text.indexOf("export {"));
    expect(tail).toContain("export { makeConf };");
    // No inline export on the function declaration itself.
    expect(text).not.toContain("export function makeConf");
  });

  it("is deterministic across calls", async () => {
    const a = await buildConfFixture(schema);
    const b = await buildConfFixture(schema);
    expect(a).toBe(b);
  });

  it("renders every JSON value shape formatValue can receive", async () => {
    const text = await buildConfFixture(schema);
    expect(text).toMatch(/n_classes: 6,/);
    expect(text).toMatch(/label_show: true,/);
    expect(text).toMatch(/groups: \[\],/);
    expect(text).toMatch(/schemes: \["Blues", "Reds"\],/);
    expect(text).toMatch(/label_format: \{ digits: 2 \},/);
  });
});

describe("main", () => {
  let dir: string | undefined;

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it("reads --json and writes the generated fixture to --out", async () => {
    dir = mkdtempSync(join(tmpdir(), "gen-conf-fixture-"));
    const jsonPath = join(dir, "conf-schema.json");
    const outPath = join(dir, "conf-fixture.ts");
    writeFileSync(jsonPath, JSON.stringify(schema), "utf-8");

    await main({ json: jsonPath, out: outPath });

    const text = readFileSync(outPath, "utf-8");
    expect(text).toContain("AUTO-GENERATED by script/gen-conf-fixture.mjs");
    expect(text).toContain("export { makeConf };");
    expect(text).toMatch(/filename: "map"/);
    expect(text).toMatch(/filename: "measurements"/);
  });
});

describe("resolveSchemaJson", () => {
  it("resolves --json over the build's scratch copy", () => {
    expect(resolveSchemaJson({ json: "x.json" })).toBe(resolve("x.json"));
  });

  it("falls back to the build's scratch copy when --json is omitted", () => {
    // The globalSetup's generator run creates this file, so it exists by the
    // time tests execute; this pins the contract on its path.
    expect(resolveSchemaJson({})).toBe(
      resolve(process.cwd(), "foliplus", ".build", "js", "conf-schema.json"),
    );
  });
});
