// AUTO-GENERATED by script/build/emit-config-schema.mjs from foliplus/_config_schema.py.
// Do not edit by hand — regenerate with:
//   python foliplus/_config_schema.py --out foliplus/.build/js/config-schema.json
//   node script/build/emit-config-schema.mjs --json foliplus/.build/js/config-schema.json
// Per-control CONF interfaces plus a flat ComponentConfig for backward
// compatibility with the existing global.d.ts shape. All fields are
// optional in ComponentConfig (any control may omit any field); per-
// control interfaces are stricter and use the schema's optional flag.
import type { ControlPosition } from "leaflet";
import type { ProviderConfig } from "#core/geocode/type.js";
import type { NumberStyle } from "#common/format.js";
import type { LocaleTables } from "#common/locale.js";

interface ConfigCommon {
  name: string; // Control class name (Python self._name).
  position?: ControlPosition; // Leaflet control position.
  locale_tables?: LocaleTables; // Locale tables written by BaseControl._config_block.
  locale_code?: string; // Resolved locale code (empty when unset).
}

interface ConfigExport extends ConfigCommon {
  filename: string;
  format: "png" | "jpeg" | "webp" | "geotiff";
  quality: number;
  scale: number;
  max_pixels: number | null; // Null disables the pixel limit.
  timeout: number;
}

interface ConfigFullscreen extends ConfigCommon {
  hide_self: boolean;
  hide_others: boolean;
}

interface ConfigHeatmap extends ConfigCommon {
  color_scheme: string;
  method: "jenks" | "quantile" | "equal" | "heads";
  n_classes: number;
  agg: "count" | "sum" | "avg" | "min" | "max";
  schemes?: string[]; // Available color scheme names.
  border_weight: number;
  border_color: string;
  fill_opacity: number;
  border_opacity: number;
  label_show: boolean;
  label_color: string;
  label_size: number;
  label_format: NumberStyle; // Number format for hexagon value labels.
  collapse_on_outside: boolean;
}

interface ConfigLayer extends ConfigCommon {
  label_collide: boolean;
  collapse_on_outside: boolean;
  /** Layer list collected from the parent map at render time via _extra_config. */
  data?: Array<{ name: string; id: string; group: "base" | "overlay" }>;
}

interface ConfigLocate extends ConfigCommon {
  zoom: number;
}

interface ConfigMeasure extends ConfigCommon {
  show_bearing: boolean;
  label_show: boolean;
  label_collide: boolean;
  show_live_coords: boolean;
  filename: string;
  export_format: "geojson" | "csv"; // MeasureControl export format.
  collapse_on_outside: boolean;
}

interface ConfigScale extends ConfigCommon {
  show_zoom: boolean;
}

interface ConfigSearch extends ConfigCommon {
  mode: "coord" | "addr"; // Default search mode on first open.
  zoom: number;
  provider: string | ProviderConfig; // Built-in provider id or a custom ProviderConfig dict.
  /** Overrides for a built-in provider; only valid with a string provider. */
  provider_config?: Record<string, unknown> | null;
  collapse_on_outside: boolean;
}

interface ConfigRuntimeOnly {
  field?: string; // Annotation field name (JS reads per-layer config, not CONF).
  background?: string; // Export background color (currently declared but unread).
}

/** Flat CONF type for all controls. All fields optional except `name`. */
interface ComponentConfig {
  name: string; // Control class name (Python self._name).
  position?: ControlPosition; // Leaflet control position.
  locale_tables?: LocaleTables; // Locale tables written by BaseControl._config_block.
  locale_code?: string; // Resolved locale code (empty when unset).
  filename?: string;
  format?: "png" | "jpeg" | "webp" | "geotiff";
  quality?: number;
  scale?: number;
  max_pixels?: number | null; // Null disables the pixel limit.
  timeout?: number;
  hide_self?: boolean;
  hide_others?: boolean;
  color_scheme?: string;
  method?: "jenks" | "quantile" | "equal" | "heads";
  n_classes?: number;
  agg?: "count" | "sum" | "avg" | "min" | "max";
  schemes?: string[]; // Available color scheme names.
  border_weight?: number;
  border_color?: string;
  fill_opacity?: number;
  border_opacity?: number;
  label_show?: boolean;
  label_color?: string;
  label_size?: number;
  label_format?: NumberStyle; // Number format for hexagon value labels.
  collapse_on_outside?: boolean;
  label_collide?: boolean;
  /** Layer list collected from the parent map at render time via _extra_config. */
  data?: Array<{ name: string; id: string; group: "base" | "overlay" }>;
  zoom?: number;
  show_bearing?: boolean;
  show_live_coords?: boolean;
  export_format?: "geojson" | "csv"; // MeasureControl export format.
  show_zoom?: boolean;
  mode?: "coord" | "addr"; // Default search mode on first open.
  provider?: string | ProviderConfig; // Built-in provider id or a custom ProviderConfig dict.
  /** Overrides for a built-in provider; only valid with a string provider. */
  provider_config?: Record<string, unknown> | null;
  field?: string; // Annotation field name (JS reads per-layer config, not CONF).
  background?: string; // Export background color (currently declared but unread).
  /** Escape hatch for truly dynamic keys not in the schema. */
  [key: string]: unknown;
}

export type {
  ConfigCommon,
  ConfigExport,
  ConfigFullscreen,
  ConfigHeatmap,
  ConfigLayer,
  ConfigLocate,
  ConfigMeasure,
  ConfigScale,
  ConfigSearch,
  ConfigRuntimeOnly,
  ComponentConfig,
};
