/**
 * Shared runtime for foliplus map controls.
 *
 * Bundled once into `dist/foliplus-common.min.js` and injected by BaseControl
 * into the shared header. Exposes:
 *   - `foliplus.geocode` / `foliplus.reverseGeocode` — global geocoding (bidirectional cache)
 *   - `foliplus.core` / `foliplus.common.<module>` — shared modules, registered
 *     automatically by script/build.mjs (see `generateSharedRegistry`) so new
 *     core/common modules need no manual wiring here.
 *   - `foliplus.BaseControl` — base class shared by all components.
 *   - `foliplus.hint` — module-level hint icon registry (per-map hint lives on map.foliplus)
 *
 * Component bundles externalize #core/* and #common/* imports to these globals
 * (see script/shared-external.mjs), so shared code is included exactly once
 * instead of being inlined into every component.
 */
import * as hintCore from "#core/hint.js";
import * as BaseControl from "#foliplus/BaseControl.js";
import { geocode, reverseGeocode } from "./geocode.js";
// Generated by build.mjs: registers window.foliplus.core / .common.<module>.
// The file only exists inside .build/ (see generateSharedRegistry) — ts-ignore
// keeps the source tree clean while esbuild resolves it at build time.
// @ts-ignore
import "../_shared-registry.js";

// Ensure the global namespace object exists.
if (!window.foliplus || typeof window.foliplus !== "object")
  window.foliplus = {} as Foliplus;
const foliplus = window.foliplus;

// Bail out if the shared runtime has already been initialized (it is inlined
// once per map, but this guard keeps it idempotent across reloads/embeds).
if (!foliplus.isInitialized) {
  foliplus.isInitialized = true;

  Object.assign(window.foliplus, {
    // Global geocoding (shared bidirectional cache + throttle).
    geocode,
    reverseGeocode,
    // BaseControl base class (shared by all components).
    BaseControl,
    // Hint module (per-map HintManager factory + shared icon registry).
    hint: hintCore,
  });
}
