/**
 * Shared runtime for foliplus map controls.
 *
 * Bundled once into dist/foliplus-common.min.js and injected by BaseControl
 * into the shared header. Exposes:
 *   - foliplus.geocode / foliplus.reverseGeocode - global geocoding (bidirectional cache)
 *   - foliplus.core / foliplus.common.<module> - shared modules, registered
 *     automatically by script/build.mjs (see generateSharedRegistry) so new
 *     core/common modules need no manual wiring here.
 *   - foliplus.BaseControl - base class shared by all components.
 *   - foliplus.hint - module-level hint icon registry (per-map hint lives on map.foliplus)
 *
 * Component bundles externalize #core/* and #common/* imports to these globals
 * (see script/shared-external.mjs), so shared code is included exactly once
 * instead of being inlined into every component.
 *
 * Geocoding helpers (NOMINATIM, nominatimUrl, formatAddress) live in
 * common/geocode.js and are statically imported by components.
 */
import { Cache } from "#common/cache.js";
import { fromWgs84, getMapCrsType, toWgs84 } from "#common/coord.js";
import { GEODECODE_TIMEOUT_MS, fetchWithTimeout } from "#common/fetch.js";
import { NOMINATIM, formatAddress, nominatimUrl } from "#common/geocode.js";
import { COMPONENTS, assertComponentName, generateId } from "#core/component.js";
import {
  HINT_DURATION,
  HintManager,
  ensureHint,
  registerHintIcon,
} from "#core/hint.js";
import { ModeManager, ensureModes, guardBlocked } from "#core/mode.js";
import { BaseControl } from "#foliplus/BaseControl.js";
// Generated by build.mjs: registers window.foliplus.core / .common.<module>.
// The file only exists inside .build/ (see generateSharedRegistry) - ts-ignore
// keeps the source tree clean while esbuild resolves it at build time.
// @ts-ignore
import "../_shared-registry.js";

// -- Geocoding (stateful singleton) --
// Bidirectional global cache: address -> coordinates (forward) and
// coordinates -> address (reverse). Shared cache + throttle queue must be
// global once per map (Nominatim rate limit is global, not per-map).

// FIFO cache shared by both directions, bounded to bound memory.
// Entries expire after 24h so Nominatim result changes are not served stale.
const GEO_CACHE_MAX = 500;
const GEO_TTL_MS = 24 * 60 * 60 * 1000;
const geoCache = new Cache<string, string>(GEO_CACHE_MAX, GEO_TTL_MS);
let geoPromise: Promise<unknown> = Promise.resolve();
let geoLastReq = 0;

/** Serialize requests through a throttled queue (Nominatim 1 req/s). */
const throttled = <T>(fn: () => Promise<T>): Promise<T> => {
  geoPromise = geoPromise.then(() => {
    const wait = Math.max(0, NOMINATIM.THROTTLE_MS - (Date.now() - geoLastReq));
    return new Promise(r => setTimeout(r, wait));
  });
  return geoPromise.then(() => {
    geoLastReq = Date.now();
    return fn();
  });
};

const localeFallback = (code: string, key: string, fallback: string) => {
  const foliplus = window.foliplus || {};
  const common = (foliplus && foliplus._TABLES && foliplus._TABLES[code]) || {};
  return common[key] || fallback;
};

/** Reverse geocode coordinates to an address via Nominatim (cached, throttled). */
const reverseGeocode = (
  map: L.Map,
  lng: number | string,
  lat: number | string,
  code = "en",
): Promise<string> => {
  const key = "reverse:" + lng + "," + lat;
  const cached = geoCache.get(key);
  if (cached) return Promise.resolve(cached);

  const wgs = toWgs84(map, parseFloat(String(lng)), parseFloat(String(lat)));
  const url = nominatimUrl(
    "/reverse",
    { lon: wgs[0], lat: wgs[1], zoom: NOMINATIM.ZOOM },
    code,
  );
  const notFound = localeFallback(code, "foliplus.addr_not_found", "Address not found");
  const fail = localeFallback(code, "foliplus.geo_fail", "Lookup failed");

  return throttled(() =>
    fetchWithTimeout(url, { timeoutMs: GEODECODE_TIMEOUT_MS })
      .then(r => r.json())
      .then(data => {
        const addr = formatAddress(data.display_name, map, code) || notFound;
        geoCache.set(key, addr);
        return addr;
      })
      .catch(() => fail),
  );
};

/** A resolved forward-geocode result. */
interface GeocodeResult {
  lat: number;
  lng: number;
  display_name: string;
}

/** Forward geocode an address to coordinates via Nominatim (cached, throttled). */
const geocode = (
  map: L.Map,
  address: string,
  code = "en",
): Promise<GeocodeResult | null> => {
  // CRS-aware key so the same address on different maps (e.g. GCJ02 vs
  // WGS84) do not share a stale cached result.
  const crs = getMapCrsType(map);
  const key = "forward:" + address + ":" + crs;
  const cached = geoCache.get(key);
  if (cached) {
    const [lat, lng, ...name] = cached.split("\u0001");
    if (name.length)
      return Promise.resolve({
        lat: +lat,
        lng: +lng,
        display_name: name.join("\u0001"),
      });
  }

  const url = nominatimUrl("/search", { q: address, limit: 1, format: "jsonv2" }, code);

  return throttled(() =>
    fetchWithTimeout(url, { timeoutMs: GEODECODE_TIMEOUT_MS })
      .then(r => r.json())
      .then((data: Array<{ lat: string; lon: string; display_name: string }>) => {
        const first = Array.isArray(data) ? data[0] : null;
        if (!first) return null;
        // Nominatim always returns WGS84 - convert to the map CRS so
        // downstream code (SearchControl, etc.) always gets coordinates
        // in the same CRS as map-displayed coordinates.
        const [lng, lat] = fromWgs84(map, parseFloat(first.lon), parseFloat(first.lat));
        const result: GeocodeResult = {
          lat,
          lng,
          display_name: first.display_name,
        };
        geoCache.set(
          key,
          result.lat + "\u0001" + result.lng + "\u0001" + result.display_name,
        );
        return result;
      })
      .catch(() => null),
  );
};

// -- Global namespace bootstrap --
// Ensure the global namespace object exists.
if (!window.foliplus || typeof window.foliplus !== "object")
  window.foliplus = {} as Foliplus;
const foliplus = window.foliplus;

// Bail out if the shared runtime has already been initialized (it is inlined
// once per map, but this guard keeps it idempotent across reloads/embeds).
if (!foliplus.isInitialized) {
  foliplus.isInitialized = true;

  Object.assign(window.foliplus, {
    // Global geocoding (shared bidirectional cache + throttle).
    geocode,
    reverseGeocode,
    // BaseControl base class (shared by all components).
    BaseControl: { BaseControl },
    // Hint module (per-map HintManager factory + shared icon registry).
    hint: { ensureHint, HINT_DURATION, HintManager, registerHintIcon },
  });

  // Core module - single file, manually registered.
  if (!foliplus.core) foliplus.core = {};
  foliplus.core.component = { COMPONENTS, assertComponentName, generateId };
  // Mode module — single file, manually registered.
  foliplus.core.mode = { ensureModes, guardBlocked, ModeManager };
}

export { geocode, reverseGeocode, type GeocodeResult };
