#!/usr/bin/env node
/**
 * Build script — minify foliplus JS/CSS assets with esbuild.
 *
 * Pipeline:
 *   1. Mirror ``foliplus/js/`` → ``foliplus/.build/``
 *   2. SVGO-compress SVG strings + minify HTML template literals (via ``script/compress.mjs``)
 *   3. esbuild-bundle each component → ``dist/foliplus-{Name}.min.js`` + ``.min.css``
 *   4. Merge ``common.css`` + ``panel.css`` → ``dist/foliplus-common.min.css``
 *
 * Usage:
 *   node script/build.mjs              # build all (minified)
 *   node script/build.mjs --dev        # unminified, keepNames (for PY identifier tests)
 *   node script/build.mjs --check      # build and verify all artifacts exist
 */
import autoprefixer from "autoprefixer";
import { spawnSync } from "child_process";
import { build } from "esbuild";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "fs";
import { basename, dirname, resolve } from "path";
import postcss from "postcss";
import postcssNesting from "postcss-nesting";
import { fileURLToPath } from "url";
import { transformSource } from "./compress.mjs";
import { sharedExternalPlugin } from "./shared-external.mjs";

// ── Config ──────────────────────────────────────────────────────
// Central path/flag config. `dev` toggles minification & identifier
// preservation — Python render-string tests rely on `keepNames` finding
// `foliplus.showHint` etc. in unminified bundles.
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const CFG = {
  src: {
    js: resolve(ROOT, "foliplus/js"),
    css: resolve(ROOT, "foliplus/css"),
  },
  out: {
    dist: resolve(ROOT, "foliplus/dist"),
  },
  tmp: {
    js: resolve(ROOT, "foliplus/.build/js"),
    css: resolve(ROOT, "foliplus/.build/css"),
  },
  mergedCssName: "_common_merged.css",
  dev: process.argv.includes("--dev"),
  check: process.argv.includes("--check"),
};

// ── Version banner ────────────────────────────────────────────────────────────
// Prefer the installed package version (foliplus.__version__, generated by
// setuptools-scm into foliplus/_version.py at install time), fall back to
// ` + "`git describe`" + ` (setuptools-scm derives the same value), then "unknown".
const resolveVersion = () => {
  const py = spawnSync(
    "python",
    ["-c", "import foliplus; print(foliplus.__version__)"],
    { encoding: "utf-8" },
  );
  if (py.status === 0 && py.stdout.trim()) return py.stdout.trim();
  const git = spawnSync(
    "git",
    ["describe", "--tags", "--always", "--dirty"],
    { encoding: "utf-8" },
  );
  if (git.status === 0 && git.stdout.trim()) return git.stdout.trim();
  return "unknown";
};
const BUILD_VERSION = resolveVersion();

// ── PostCSS pipeline ────────────────────────────────────────────
// CSS sources are authored in nested syntax (CSS Nesting) and compiled to
// flat selectors for maximum browser compatibility, then vendor-prefixed
// via Autoprefixer (driven by the `browserslist` key in package.json).
// `edition: '2021'` emits fully-flattened selectors (no `:is()` wrapper),
// keeping specificity identical to hand-written flat CSS.
const postcssProcessor = postcss([postcssNesting({ edition: "2021" }), autoprefixer()]);

/** esbuild onLoad plugin that runs CSS through the PostCSS pipeline. */
const postcssPlugin = {
  name: "postcss",
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, async args => {
      const source = readFileSync(args.path, "utf-8");
      const result = await postcssProcessor.process(source, { from: args.path });
      return { contents: result.css, loader: "css" };
    });
  },
};

// ── Shared esbuild options ──────────────────────────────────────
// `alias` maps `#common/*` to the processed `.build/` copy so compressed
// sources are bundled (not the raw `foliplus/js` originals).
const esbuildCfg = {
  bundle: true,
  format: "iife",
  minify: !CFG.dev,
  // Sourcemaps are only useful when debugging the minified bundle in a browser.
  // Since foliplus bundles are embedded in Python-generated HTML and shipped
  // to end users, production sourcemaps have no consumer — skip them.
  sourcemap: false,
  allowOverwrite: true,
  keepNames: CFG.dev,
  alias: {
    "#common": CFG.tmp.js + "/common",
    "#core": CFG.tmp.js + "/core",
    "#foliplus": CFG.tmp.js,
  },
  plugins: [postcssPlugin],
};

const artifact = (entryPoints, outfile, name) => ({
  entryPoints,
  outfile,
  ...esbuildCfg,
  // P5: shared modules (#core/#common/#foliplus/BaseControl) are externalized
  // in component bundles and read from the global namespace; the runtime entry
  // itself bundles them (no externalization).
  plugins:
    name === "runtime"
      ? esbuildCfg.plugins
      : [...esbuildCfg.plugins, sharedExternalPlugin(CFG.tmp.js)],
  banner: {
    js: `/*! foliplus@${BUILD_VERSION} · ${name} */\n`,
    css: `/*! foliplus@${BUILD_VERSION} · ${name} */\n`,
  },
});

/** Recursively apply source transforms (SVGO + HTML minify) to every JS/TS file. */
const processJsFiles = dir => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) processJsFiles(full);
    else if (entry.name.endsWith(".js") || entry.name.endsWith(".ts"))
      writeFileSync(full, transformSource(readFileSync(full, "utf-8")), "utf-8");
  }
};

/** Return the first path that exists, else null. */
const resolveEntry = candidates => candidates.find(existsSync) ?? null;

/** Discover component entries (dirs with a matching `{Name}.{ts|js}`) under .build/. */
const findComponents = () => {
  const entries = readdirSync(CFG.tmp.js, { withFileTypes: true });
  const components = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name === "shared" || entry.name === "core") continue; // shared, not a control component
    const name = entry.name;
    const jsFile = resolveEntry([
      resolve(CFG.tmp.js, name, "index.ts"),
      resolve(CFG.tmp.js, name, "index.js"),
    ]);
    const cssFile = resolve(CFG.src.css, `${name}.css`);
    if (jsFile)
      components.push({ name, js: jsFile, css: existsSync(cssFile) ? cssFile : null });
  }
  return components;
};

/** Shorthand for a path under dist/. */
const out = name => resolve(CFG.out.dist, name);

/** Build the full list of esbuild artifacts (components + merged common CSS). */
const buildEntries = components => {
  const entries = [];
  for (const { name, js, css } of components) {
    // "runtime" is the shared JS (hint/geocode global state); expose it as
    // "common" so the filename foliplus-common.min.js pairs with the CSS.
    const outName = name === "runtime" ? "common" : name;
    entries.push(artifact([js], out(`foliplus-${outName}.min.js`), name));
    if (css) entries.push(artifact([css], out(`foliplus-${outName}.min.css`), name));
  }

  // Merge common.css + panel.css into a single artifact
  const commonCss = resolve(CFG.src.css, "common.css");
  const panelCss = resolve(CFG.src.css, "panel.css");
  if (existsSync(commonCss)) {
    let css = readFileSync(commonCss, "utf-8");
    if (existsSync(panelCss)) css += "\n" + readFileSync(panelCss, "utf-8");
    mkdirSync(CFG.tmp.css, { recursive: true });
    const tmpCss = resolve(CFG.tmp.css, CFG.mergedCssName);
    writeFileSync(tmpCss, css, "utf-8");
    entries.push(artifact([tmpCss], out("foliplus-common.min.css"), "common"));
  }
  return entries;
};

/** Generate .build/js/_shared-registry.ts — registers every shared module on
 *  window.foliplus (core → foliplus.core, each common module → foliplus.common.<name>).
 *  Scans the mirrored sources so new core/common modules are picked up
 *  automatically (no manual wiring in runtime/index.ts). */
const generateSharedRegistry = () => {
  const commonDir = resolve(CFG.tmp.js, "common");
  const coreDir = resolve(CFG.tmp.js, "core");
  const commonModules = readdirSync(commonDir)
    .filter(f => f.endsWith(".ts") && f !== "index.ts")
    .map(f => f.replace(/\.ts$/, ""))
    .sort();
  // core subdomains (core/layer, future core/events, core/modes, ...) — each
  // exposes its barrel as foliplus.core.<subdomain>.
  const coreSubs = readdirSync(coreDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();
  const lines = [
    "// AUTO-GENERATED by script/build.mjs — do not edit.",
    "// Registers shared modules on window.foliplus for externalized component bundles.",
    'window.foliplus = window.foliplus || {};',
    "window.foliplus.core = {};",
    "window.foliplus.common = {};",
  ];
  for (const sub of coreSubs) {
    lines.push(`import * as core${sub} from "#core/${sub}/index.js";`);
    lines.push(`window.foliplus.core["${sub}"] = core${sub};`);
  }
  for (const name of commonModules) {
    lines.push(`import * as ${name} from "#common/${name}.js";`);
    lines.push(`window.foliplus.common["${name}"] = ${name};`);
  }
  writeFileSync(resolve(CFG.tmp.js, "_shared-registry.ts"), lines.join("\n"), "utf-8");
};

async function main() {
  // ── Step 1: Mirror source to .build/ ──────────────────────────
  // Process in a temp directory so the original source is untouched.
  rmSync(resolve(CFG.tmp.js, ".."), { recursive: true, force: true });
  mkdirSync(CFG.tmp.js, { recursive: true });
  cpSync(CFG.src.js, CFG.tmp.js, { recursive: true });

  // ── Step 2: Source transforms ─────────────────────────────────
  // SVG compression + HTML template minification (in-place on .build/ copy).
  processJsFiles(CFG.tmp.js);

  // ── Step 2.5: Generate shared registry ────────────────────────
  // Auto-registers every common/core module on window.foliplus (P5).
  generateSharedRegistry();

  // ── Step 3: Discover components & build entries ───────────────
  const components = findComponents();
  const entries = buildEntries(components);
  console.log(
    `Building ${entries.length} artifacts for ${components.length} components...`,
  );

  // ── Step 4: esbuild bundle (parallel) ─────────────────────────
  const results = await Promise.allSettled(entries.map(opts => build(opts)));
  const failed = results.filter(r => r.status === "rejected").length;
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    if (r.status === "fulfilled") console.log(`  ✓ ${basename(entries[i].outfile)}`);
    else console.error(`  ✗ ${basename(entries[i].outfile)}: ${r.reason.message}`);
  }

  // ── Step 5: Verification (--check) ────────────────────────────
  if (CFG.check) {
    const missing = entries.map(e => e.outfile).filter(f => !existsSync(f));
    if (missing.length) {
      console.error(`Missing artifacts: ${missing.join(", ")}`);
      process.exit(1);
    }
    console.log(`All ${entries.length} artifacts present.`);
  }
  if (failed) process.exit(1);
  console.log("Done.");
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
