#!/usr/bin/env node
/**
 * Build script — minify foliplus JS/CSS assets with esbuild.
 *
 * Pipeline:
 *   1. Mirror ``foliplus/js/`` → ``foliplus/.build/``
 *   2. SVGO-compress SVG strings + minify HTML template literals (via ``script/compress.mjs``)
 *   3. esbuild-bundle each component → ``dist/foliplus-{Name}.min.js`` + ``.min.css``
 *   4. Merge ``common.css`` + ``panel.css`` → ``dist/foliplus-common.min.css``
 *
 * Usage:
 *   node script/build.mjs              # build all (minified)
 *   node script/build.mjs --dev        # unminified, keepNames (for PY identifier tests)
 *   node script/build.mjs --check      # build and verify all artifacts exist
 */
import autoprefixer from "autoprefixer";
import { spawnSync } from "child_process";
import { build } from "esbuild";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "fs";
import { basename, dirname, resolve } from "path";
import postcss from "postcss";
import postcssNesting from "postcss-nesting";
import { fileURLToPath } from "url";
import { transformSource } from "./compress.mjs";
import { globalNamespacePlugin } from "./global-namespace-plugin.mjs";

// ── Config ──────────────────────────────────────────────────────
// Central path/flag config. `dev` toggles minification & identifier
// preservation — Python render-string tests rely on `keepNames` finding
// `foliplus.showHint` etc. in unminified bundles.
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
// The shared-runtime directory is bundled as foliplus-common.min.js and
// must NOT be externalized (it bundles the shared modules).
const SHARED_ENTRY = "runtime";

const CFG = {
  src: {
    js: resolve(ROOT, "foliplus/js"),
    css: resolve(ROOT, "foliplus/css"),
  },
  out: {
    dist: resolve(ROOT, "foliplus/dist"),
  },
  tmp: {
    js: resolve(ROOT, "foliplus/.build/js"),
    css: resolve(ROOT, "foliplus/.build/css"),
  },
  mergedCssName: "_common_merged.css",
  dev: process.argv.includes("--dev"),
  check: process.argv.includes("--check"),
};

// ── Version banner ────────────────────────────────────────────────────────────
// Prefer the installed package version (foliplus.__version__, generated by
// setuptools-scm into foliplus/_version.py at install time), fall back to
// ` + "`git describe`" + ` (setuptools-scm derives the same value), then "unknown".
const resolveVersion = () => {
  const py = spawnSync(
    "python",
    ["-c", "import foliplus; print(foliplus.__version__)"],
    { encoding: "utf-8" },
  );
  if (py.status === 0 && py.stdout.trim()) return py.stdout.trim();
  const git = spawnSync("git", ["describe", "--tags", "--always", "--dirty"], {
    encoding: "utf-8",
  });
  if (git.status === 0 && git.stdout.trim()) return git.stdout.trim();
  return "unknown";
};
const BUILD_VERSION = resolveVersion();

// ── PostCSS pipeline ────────────────────────────────────────────
// CSS sources are authored in nested syntax (CSS Nesting) and compiled to
// flat selectors for maximum browser compatibility, then vendor-prefixed
// via Autoprefixer (driven by the `browserslist` key in package.json).
// `edition: '2021'` emits fully-flattened selectors (no `:is()` wrapper),
// keeping specificity identical to hand-written flat CSS.
const postcssProcessor = postcss([postcssNesting({ edition: "2021" }), autoprefixer()]);

/** esbuild onLoad plugin that runs CSS through the PostCSS pipeline. */
const postcssPlugin = {
  name: "postcss",
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, async args => {
      const source = readFileSync(args.path, "utf-8");
      const result = await postcssProcessor.process(source, { from: args.path });
      return { contents: result.css, loader: "css" };
    });
  },
};

// ── Shared esbuild options ──────────────────────────────────────
// `alias` maps `#common/*` to the processed `.build/` copy so compressed
// sources are bundled (not the raw `foliplus/js` originals).
const esbuildCfg = {
  bundle: true,
  format: "iife",
  minify: !CFG.dev,
  // Tree Shaking: drop unused exports from shared modules.
  // Only effective with targeted imports (see generateSharedRegistry below).
  treeShaking: true,
  // Sourcemaps are only useful when debugging the minified bundle in a browser.
  // Since foliplus bundles are embedded in Python-generated HTML and shipped
  // to end users, production sourcemaps have no consumer — skip them.
  sourcemap: false,
  allowOverwrite: true,
  keepNames: CFG.dev,
  alias: {
    "#common": CFG.tmp.js + "/common",
    "#core": CFG.tmp.js + "/core",
    "#foliplus": CFG.tmp.js,
  },
  plugins: [postcssPlugin],
};

const artifact = (entryPoints, outfile, name) => ({
  entryPoints,
  outfile,
  ...esbuildCfg,
  // P5: shared modules (#core/#common/#foliplus/BaseControl) are externalized
  // in component bundles and read from the global namespace; the shared entry
  // itself bundles them (no externalization).
  plugins:
    name === SHARED_ENTRY
      ? esbuildCfg.plugins
      : [...esbuildCfg.plugins, globalNamespacePlugin(CFG.tmp.js)],
  banner: {
    js: `/*! foliplus@${BUILD_VERSION} · ${name} */\n`,
    css: `/*! foliplus@${BUILD_VERSION} · ${name} */\n`,
  },
});

/** Recursively apply source transforms (SVGO + HTML minify) to every JS/TS file.
 *  Runs file transforms in parallel for faster builds. */
const processJsFiles = async dir => {
  const jobs = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      jobs.push(processJsFiles(full));
    } else if (entry.name.endsWith(".js") || entry.name.endsWith(".ts")) {
      jobs.push(
        Promise.resolve().then(() => {
          writeFileSync(full, transformSource(readFileSync(full, "utf-8")), "utf-8");
        }),
      );
    }
  }
  await Promise.all(jobs);
};

/** Return the first path that exists, else null. */
const resolveEntry = candidates => candidates.find(existsSync) ?? null;

/** Discover component entries (dirs with a matching `{Name}.{ts|js}`) under .build/. */
const findComponents = () => {
  const entries = readdirSync(CFG.tmp.js, { withFileTypes: true });
  const components = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name === "core") continue; // core is a shared subdomain, not a control component
    const name = entry.name;
    const jsFile = resolveEntry([
      resolve(CFG.tmp.js, name, "index.ts"),
      resolve(CFG.tmp.js, name, "index.js"),
    ]);
    const cssFile = resolve(CFG.src.css, `${name}.css`);
    if (jsFile)
      components.push({ name, js: jsFile, css: existsSync(cssFile) ? cssFile : null });
  }
  return components;
};

/** Shorthand for a path under dist/. */
const out = name => resolve(CFG.out.dist, name);

/** Build the full list of esbuild artifacts (components + merged common CSS). */
const buildEntries = components => {
  const entries = [];
  for (const { name, js, css } of components) {
    // The shared entry is exposed as "common" so the filename
    // foliplus-common.min.js pairs with the CSS.
    const outName = name === SHARED_ENTRY ? "common" : name;
    entries.push(artifact([js], out(`foliplus-${outName}.min.js`), name));
    if (css) entries.push(artifact([css], out(`foliplus-${outName}.min.css`), name));
  }

  // Merge common.css + panel.css into a single artifact
  const commonCss = resolve(CFG.src.css, "common.css");
  const panelCss = resolve(CFG.src.css, "panel.css");
  if (existsSync(commonCss)) {
    let css = readFileSync(commonCss, "utf-8");
    if (existsSync(panelCss)) css += "\n" + readFileSync(panelCss, "utf-8");
    mkdirSync(CFG.tmp.css, { recursive: true });
    const tmpCss = resolve(CFG.tmp.css, CFG.mergedCssName);
    writeFileSync(tmpCss, css, "utf-8");
    entries.push(artifact([tmpCss], out("foliplus-common.min.css"), "common"));
  }
  return entries;
};

/** Generate .build/js/_shared-registry.ts — auto-scans component imports
 *  for used exports from shared modules. When a component adds or removes an
 *  import, the change is automatically reflected at the next build.
 *  Uses targeted named imports (not import * as) so Tree Shaking can drop
 *  unused code. */
const generateSharedRegistry = () => {
  const commonDir = resolve(CFG.tmp.js, "common");
  const coreDir = resolve(CFG.tmp.js, "core");
  const commonModules = readdirSync(commonDir)
    .filter(f => f.endsWith(".ts") && f !== "index.ts")
    .map(f => f.replace(/\.ts$/, ""))
    .sort();
  const coreSubs = readdirSync(coreDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();
  const coreSingleFiles = readdirSync(coreDir, { withFileTypes: true })
    .filter(f => f.isFile() && f.name.endsWith(".ts") && f.name !== "index.ts")
    .map(f => f.name.replace(/\.ts$/, ""))
    .sort();

  // ── Auto-scan component imports ────────────────────────────────
  // Walk component .ts files (excluding shared dirs that would circularly
  // import themselves) and collect every VALUE export imported from
  // #common/*, #core/*, #foliplus/*. Type-only imports are excluded.
  // Also resolves * as imports to property access on the namespace.
  const srcDir = resolve(CFG.tmp.js);
  const imported = new Map(); // spec → Set of value names
  const starImported = new Map(); // spec → Set of namespace aliases

  function scanImports(dir) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = resolve(dir, entry.name);
      if (entry.isDirectory()) scanImports(full);
      else if (entry.name.endsWith(".ts") && !entry.name.endsWith(".d.ts")) {
        const src = readFileSync(full, "utf-8");
        const namedRe =
          /import[\s]*\{([^}]+)\}[\s]*from[\s]*"(#(?:common|core|foliplus)\/[^"]+)"/g;
        let m;
        while ((m = namedRe.exec(src))) {
          const spec = m[2].replace(/^#/, "").replace(/\.js$/, "");
          const names = m[1]
            .split(",")
            .map(n => n.trim())
            // Skip type-only imports (e.g. "type Debounced")
            .filter(n => !n.startsWith("type"))
            .map(n => n.replace(/[\s]+as[\s]+.*/g, ""))
            .filter(Boolean);
          if (!imported.has(spec)) imported.set(spec, new Set());
          names.forEach(n => imported.get(spec).add(n));
        }
        const starRe =
          /import[\s]+\*[\s]+as[\s]+(\w+)[\s]+from[\s]*"(#(?:common|core)\/[^"]+)"/g;
        while ((m = starRe.exec(src))) {
          const spec = m[2].replace(/^#/, "").replace(/\.js$/, "");
          if (!starImported.has(spec)) starImported.set(spec, new Set());
          starImported.get(spec).add(m[1]);
        }
      }
    }
  }

  const componentDirs = readdirSync(srcDir, { withFileTypes: true })
    .filter(e => e.isDirectory() && !["core", "common", "type", "runtime"].includes(e.name))
    .map(e => resolve(srcDir, e.name));
  for (const dir of componentDirs) scanImports(dir);

  // ── Resolve * as imports to property access ────────────────────
  // For each * as alias, scan for alias.PropertyName and alias.methodName
  // accesses to determine which exports are actually used at runtime.
  for (const [spec, aliases] of starImported) {
    if (!imported.has(spec)) imported.set(spec, new Set());
    for (const alias of aliases) {
      for (const dir of componentDirs) {
        const files = readdirSync(dir, { withFileTypes: true })
          .filter(e => e.isFile() && e.name.endsWith(".ts"))
          .map(e => resolve(dir, e.name));
        for (const file of files) {
          const src = readFileSync(file, "utf-8");
          // Only SCREAMING_NAMES: Icons.CLOSE, Storage.load, Storage.save
          const upperRe = new RegExp(alias + "[.]" + "([A-Z][A-Z0-9_]*)", "g");
          let pm;
          while ((pm = upperRe.exec(src))) imported.get(spec).add(pm[1]);
          // Known Storage methods (lowercase): Storage.load, Storage.save
          if (alias === "Storage") {
            const stdRe = new RegExp(alias + "[.]" + "(load|save)", "g");
            let sm;
            while ((sm = stdRe.exec(src))) imported.get(spec).add(sm[1]);
          }
        }
      }
    }
  }

  const usedExports = {};
  for (const [spec, names] of imported) {
    usedExports[spec] = [...names].sort();
  }

  const lines = [
    "// AUTO-GENERATED by script/build.mjs — do not edit.",
    "// Scans component imports for targeted named imports (Tree Shaking).",
    "window.foliplus = window.foliplus || {};",
    "window.foliplus.core = {};",
    "window.foliplus.common = {};",
  ];

  for (const sub of coreSubs) {
    const names = usedExports["core/" + sub] || [];
    if (names.length === 0) continue;
    const alias = "core" + sub;
    lines.push("import { " + names.join(", ") + " } from \"#core/" + sub + "/index.js\";");
    lines.push("const " + alias + " = { " + names.join(", ") + " };");
    lines.push('window.foliplus.core["' + sub + '"] = ' + alias + ';');
  }

  for (const name of coreSingleFiles) {
    const names = usedExports["core/" + name] || [];
    if (names.length === 0) continue;
    const alias = "core" + name;
    lines.push("import { " + names.join(", ") + " } from \"#core/" + name + ".js\";");
    lines.push("const " + alias + " = { " + names.join(", ") + " };");
    lines.push('window.foliplus.core["' + name + '"] = ' + alias + ';');
  }

  for (const name of commonModules) {
    const names = usedExports["common/" + name] || [];
    if (names.length === 0) continue;
    lines.push("import { " + names.join(", ") + " } from \"#common/" + name + ".js\";");
    lines.push("const " + name + "NS = { " + names.join(", ") + " };");
    lines.push('window.foliplus.common["' + name + '"] = ' + name + 'NS;');
  }

  const baseNames = usedExports["foliplus/BaseControl"] || ["BaseControl"];
  if (baseNames.length > 0) {
    lines.push("import { " + baseNames.join(", ") + " } from \"#foliplus/BaseControl.js\";");
    lines.push("const BaseControlNS = { " + baseNames.join(", ") + " };");
    lines.push("window.foliplus.BaseControl = BaseControlNS.BaseControl;");
  }

  writeFileSync(resolve(CFG.tmp.js, "_shared-registry.ts"), lines.join("\n"), "utf-8");
};
async function main() {
  console.time("build");
  // ── Step 1: Mirror source to .build/ ──────────────────────────
  // Process in a temp directory so the original source is untouched.
  rmSync(resolve(CFG.tmp.js, ".."), { recursive: true, force: true });
  mkdirSync(CFG.tmp.js, { recursive: true });
  cpSync(CFG.src.js, CFG.tmp.js, { recursive: true });

  // ── Step 2: Source transforms ─────────────────────────────────
  // SVG compression + HTML template minification (in-place on .build/ copy).
  await processJsFiles(CFG.tmp.js);

  // ── Step 2.5: Generate shared registry ────────────────────────
  // Auto-registers every common/core module on window.foliplus (P5).
  generateSharedRegistry();

  // ── Step 3: Discover components & build entries ───────────────
  const components = findComponents();
  const entries = buildEntries(components);
  console.log(
    `Building ${entries.length} artifacts for ${components.length} components...`,
  );

  // ── Step 4: esbuild bundle (parallel) ─────────────────────────
  const results = await Promise.allSettled(entries.map(opts => build(opts)));
  const failed = results.filter(r => r.status === "rejected").length;
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    if (r.status === "fulfilled") console.log(`  ✓ ${basename(entries[i].outfile)}`);
    else console.error(`  ✗ ${basename(entries[i].outfile)}: ${r.reason.message}`);
  }

  // ── Step 5: Verification (--check) ────────────────────────────
  if (CFG.check) {
    const missing = entries.map(e => e.outfile).filter(f => !existsSync(f));
    if (missing.length) {
      console.error(`Missing artifacts: ${missing.join(", ")}`);
      process.exit(1);
    }
    console.log(`All ${entries.length} artifacts present.`);
  }
  if (failed) process.exit(1);
  console.timeEnd("build");
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});