/**
 * Resolve the foliplus package version for build banners and the size baseline.
 *
 * Prefer the installed package version (`foliplus.__version__`, generated by
 * setuptools-scm into `foliplus/_version.py` at install time), fall back to
 * `git describe` (setuptools-scm derives the same value), then "unknown".
 * Shared by `build.mjs` and `bundle-size-check.mjs`.
 */
import { spawnSync } from "child_process";

let versionCache = null;

export const resolveVersion = () => {
  if (versionCache) return versionCache;
  const py = spawnSync(
    "python",
    ["-c", "import foliplus; print(foliplus.__version__)"],
    { encoding: "utf-8" },
  );
  if (py.status === 0 && py.stdout.trim()) {
    versionCache = py.stdout.trim();
    return versionCache;
  }
  const git = spawnSync("git", ["describe", "--tags", "--always", "--dirty"], {
    encoding: "utf-8",
  });
  if (git.status === 0 && git.stdout.trim()) {
    versionCache = git.stdout.trim();
    return versionCache;
  }
  versionCache = "unknown";
  return versionCache;
};
