name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.python }}, ${{ matrix.env }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        env: [ci/env/latest.yaml]
    steps:
      - uses: actions/checkout@v6
      - uses: mamba-org/setup-micromamba@v3.0.0
        with:
          environment-file: ${{ matrix.env }}
          create-args: python=${{ matrix.python }}

      - run: playwright install chromium
      - run: pip install -e .
      - run: make info
      - run: make test

      - uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
